// src/content/hubs/facial-treatments.ts

import type { SEOMeta, ServiceCard, HubSubPillarCard, FAQItem } from "@/types/content";

export const seo: SEOMeta = {
  title: "Facial Treatments | Hydrofacial, Peels & Anti-Aging | Essence Medspa Chicago",
  description: "21 customized facial treatments including Hydrofacial ($229), RF Micro-Needling ($399), Jet Plasma ($350), chemical peels, and our Signature Facelift Facial at Essence Medspa Chicago.",
  keywords: ["facial treatments Chicago", "Hydrofacial near me", "chemical peel Chicago", "anti-aging facial Edgebrook", "microdermabrasion Chicago"],
  canonical: "https://www.essence-medspa.com/services/facial-treatments",
  ogImage: "/images/og/facial-treatments.jpg",
};

export const hero = {
  eyebrow: "Facial Treatments",
  headline: "21 Facials. One Perfect Match for Your Skin.",
  subheadline: "From deep-cleansing basics to advanced RF micro-needling, every facial is customized to your skin type, concerns, and goals. Walk in with questions, walk out with answers — and a glow.",
  primaryCTA: { text: "Book a Facial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" as const },
  secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" as const },
  badge: "⭐ 4.9 Stars · 463 Google Reviews",
  image: { src: "/images/hubs/facial-treatments-hero.jpg", alt: "Client receiving a luxury facial treatment at Essence Medspa Chicago" },
};

export const intro = {
  headline: "Facial Treatments at Essence",
  body: "Your face is unique — your facial should be too. Our 21 facial treatments span every skin concern from teenage acne to mature skin rejuvenation, from post-summer sun damage to pre-event glow prep. Every treatment includes a skin assessment and product recommendations so you continue seeing results at home between visits.",
};

export const services: ServiceCard[] = [
  { name: "Hydrofacial", slug: "hydrofacial", tagline: "Chicago's most requested glow treatment", description: "60-minute oxygen and water facial combining cleansing, extraction, and infusion for instant, visible radiance.", startingPrice: "$229", highlights: ["Instant glow", "Zero downtime", "All skin types"], cta: { text: "Learn More", href: "/services/hydrofacial" } },
  { name: "Custom Facial", slug: "custom-facial", tagline: "Your skin, your treatment, your results", description: "50-minute fully personalized facial tailored after a thorough skin analysis. The most flexible option for unique concerns.", startingPrice: "$169", highlights: ["Fully customized", "Skin analysis included", "50 minutes"], cta: { text: "Learn More", href: "/services/custom-facial" } },
  { name: "RF Micro-Needling Facial", slug: "rf-microneedling-facial", tagline: "Rewrite your skin's collagen framework", description: "75-minute radiofrequency micro-needling for advanced anti-aging, scar revision, and skin tightening.", startingPrice: "$399", highlights: ["Collagen remodeling", "Skin tightening", "75 minutes"], cta: { text: "Learn More", href: "/services/rf-microneedling-facial" } },
  { name: "Jet Plasma Facial", slug: "jet-plasma-facial", tagline: "Plasma-powered skin transformation", description: "30-minute plasma treatment for fine lines, acne scarring, hyperpigmentation, and overall rejuvenation.", startingPrice: "$350", highlights: ["No downtime", "Fine lines + scars", "30 minutes"], cta: { text: "Learn More", href: "/services/jet-plasma-facial" } },
  { name: "Essence Signature Facelift Facial", slug: "essence-signature-facelift-facial", tagline: "Our most transformative facial", description: "50-minute 4-layer Vitamin C treatment with AHA/BHA/enzymes to tighten, brighten, and visibly transform.", startingPrice: "$195", highlights: ["4-layer treatment", "Vitamin C infusion", "Visible lift"], cta: { text: "Learn More", href: "/services/essence-signature-facelift-facial" } },
  { name: "Essence Signature Facelift Peel", slug: "essence-signature-facelift-peel", tagline: "Our signature peel, safe for all skin types", description: "30-minute organic peel using our proprietary 4-layer facelift formula. Safe for sensitive skin.", startingPrice: "$129", highlights: ["All skin types", "Organic formula", "30 minutes"], cta: { text: "Learn More", href: "/services/essence-signature-facelift-peel" } },
  { name: "Red Carpet Collagen Anti-Wrinkle", slug: "red-carpet-collagen-facial", tagline: "80 minutes of powerful anti-aging", description: "80-minute collagen-boosting treatment that hydrates, tones, strengthens, and visibly reduces wrinkles.", startingPrice: "$215", highlights: ["Anti-wrinkle", "Collagen boost", "80 minutes"], cta: { text: "Learn More", href: "/services/red-carpet-collagen-facial" } },
  { name: "Red Carpet Signature Anti-Aging", slug: "red-carpet-anti-aging-facial", tagline: "Instant visible results, no needles", description: "60-minute non-invasive expression line treatment with immediate visible improvement. Pre-event favorite.", startingPrice: "$199", highlights: ["Instant results", "Non-invasive", "60 minutes"], cta: { text: "Learn More", href: "/services/red-carpet-anti-aging-facial" } },
  { name: "Firming Facial", slug: "firming-facial", tagline: "Visible lifting in a single session", description: "60-minute 4-step progressive treatment delivering an instant face lift effect. Ideal before special events.", startingPrice: "$215", highlights: ["Instant lift", "4-step protocol", "60 minutes"], cta: { text: "Learn More", href: "/services/firming-facial" } },
  { name: "Acne Facial", slug: "acne-facial", tagline: "Clear breakouts, calm inflammation", description: "50-minute acne treatment with ZO Stimulator Peel and sulfur mask targeting active breakouts and congestion.", startingPrice: "$159", highlights: ["Acne-specific", "ZO Stimulator Peel", "50 minutes"], cta: { text: "Learn More", href: "/services/acne-facial" } },
  { name: "Brightening Facial", slug: "brightening-facial", tagline: "Vitamin C-powered radiance", description: "50-minute antioxidant facial with Vitamin C, algae patches, and thermal organic clay for luminous skin.", startingPrice: "$155", highlights: ["Vitamin C", "Brightening", "50 minutes"], cta: { text: "Learn More", href: "/services/brightening-facial" } },
  { name: "Hydrating Facial", slug: "hydrating-facial", tagline: "Deep relief for parched skin", description: "50-minute soothing hydration treatment with thermo-cooling for sensitive and dehydrated skin.", startingPrice: "$159", highlights: ["Sensitive-safe", "Thermo-cooling", "50 minutes"], cta: { text: "Learn More", href: "/services/hydrating-facial" } },
  { name: "Oxygen Facial", slug: "oxygen-facial", tagline: "Breathe life back into your skin", description: "60-minute oxygen revival treatment delivering deep hydration, plumpness, and luminous radiance.", startingPrice: "$159", highlights: ["Deep hydration", "Oxygen infusion", "60 minutes"], cta: { text: "Learn More", href: "/services/oxygen-facial" } },
  { name: "Deep Pore Cleansing Facial", slug: "deep-pore-cleansing-facial", tagline: "The ultimate skin detox", description: "50-minute intensive pore detox with professional extractions for congested, oily, or breakout-prone skin.", startingPrice: "$125", highlights: ["Extractions", "Pore detox", "50 minutes"], cta: { text: "Learn More", href: "/services/deep-pore-cleansing-facial" } },
  { name: "Microdermabrasion Facial", slug: "microdermabrasion-facial", tagline: "Resurface and reveal", description: "50-minute crystal exfoliation for sun damage, scarring, wrinkles, age spots, and large pores.", startingPrice: "$125", highlights: ["Crystal exfoliation", "Scar + sun damage", "50 minutes"], cta: { text: "Learn More", href: "/services/microdermabrasion-facial" } },
  { name: "Microdermabrasion — Chest", slug: "microdermabrasion-chest", tagline: "Smooth and renew the décolleté", description: "45-minute chest treatment for sun damage, age spots, and fine lines on the décolleté area.", startingPrice: "$91", highlights: ["Chest area", "Sun damage", "45 minutes"], cta: { text: "Learn More", href: "/services/microdermabrasion-chest" } },
  { name: "Microdermabrasion — Neck", slug: "microdermabrasion-neck", tagline: "Targeted neck renewal", description: "20-minute neck treatment for lines, wrinkles, and uneven skin tone.", startingPrice: "$59", highlights: ["Neck area", "Quick treatment", "20 minutes"], cta: { text: "Learn More", href: "/services/microdermabrasion-neck" } },
  { name: "Custom Peel", slug: "custom-peel", tagline: "Results-driven exfoliation", description: "30-minute chemical peel customized to your skin type for pigmentation, mature skin, and fine lines.", startingPrice: "$130", highlights: ["Customized formula", "Progressive results", "30 minutes"], cta: { text: "Learn More", href: "/services/custom-peel" } },
  { name: "Collagen Sublime Eye Contour", slug: "collagen-eye-contour", tagline: "Revitalize the delicate eye area", description: "30-minute 4-step eye treatment for under-eye revitalization, nourishment, and anti-aging.", startingPrice: "$77", highlights: ["Eye-specific", "4-step protocol", "30 minutes"], cta: { text: "Learn More", href: "/services/collagen-eye-contour" } },
  { name: "Teen Facial", slug: "teen-facial", tagline: "The right start for young skin", description: "30-minute facial designed specifically for teen skin — deep cleansing, acne management, and skincare education.", startingPrice: "$85", highlights: ["Ages 13–19", "Acne management", "30 minutes"], cta: { text: "Learn More", href: "/services/teen-facial" } },
  { name: "4D Face Lifting Massage", slug: "4d-face-lifting-massage", tagline: "Non-invasive lift meets ancient technique", description: "60-minute multi-layer face lifting combining Eastern wisdom with modern skincare science.", startingPrice: "$195", highlights: ["Non-invasive lift", "Eastern + modern", "60 minutes"], cta: { text: "Learn More", href: "/services/4d-face-lifting-massage" } },
];

export const ctaSection = {
  headline: "Not Sure Which Facial Is Right for You?",
  subheadline: "Book a consultation and our aesthetician will analyze your skin and recommend the perfect facial for your specific concerns.",
  primaryCTA: { text: "Book a Facial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" as const },
  secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" as const },
};

export const deepIntro = {
  eyebrow: "The Essence Approach",
  headline: "Why Essence-grade facials don't look, feel, or finish like anywhere else.",
  body: "Most facials in Chicago are the same hour, repackaged. A cleanse, a mask, a massage, and a hopeful prayer that your skin notices. Ours don't work that way. Every treatment at Essence starts with a skin analysis by a State of Illinois licensed aesthetician — not a receptionist with a product menu. Before we choose a peel strength, a serum, or a device depth, we want to know how your skin behaves: how it reacts to Chicago's winter dry air, how it sits after a lunchtime sweat, how it recovers from the last breakout or peel you tried at home.\n\nThe products we reach for are medical-grade by default. Our Acne Facial runs on a [ZO Skin Health](/services/acne-facial) Stimulator Peel and sulfur mask protocol. Our brightening work leans on professional-grade Vitamin C paired with algae patches and thermal organic clay. Our custom peels are calibrated to your skin type — not a one-strength-fits-all solution. When collagen loss is the real issue, we bring in [RF microneedling](/services/rf-microneedling-facial), [Jet Plasma](/services/jet-plasma-facial), or our [Red Carpet Collagen](/services/red-carpet-collagen-facial) anti-wrinkle treatment — protocols you won't find on a day-spa menu.\n\nProtocol depth is where the gap widens. A generic spa facial ends at the extraction. Ours begin there. Four-layer Vitamin C [Signature Facelift](/services/essence-signature-facelift-facial) builds tension back into slackened tissue. Eighty-minute Red Carpet Collagen sessions hydrate, tone, strengthen, and visibly soften wrinkles in a single appointment. Every treatment closes with a written home-care plan so the work continues between visits — because what you do at 10 p.m. on a Tuesday matters as much as what we do on the table.\n\nFive-plus years on Chicago's Far Northwest Side, 463 five-star Google reviews, and a steady client base drawn from Edgebrook, Sauganash, Forest Glen, Lincolnwood, Park Ridge, and Niles — that's the evidence. Consultation-first, personalization always, no surprise upsells. Come with questions, leave with a plan.",
};

export const subPillarCards: HubSubPillarCard[] = [
  {
    title: "Anti-Aging Facials",
    tagline: "Reverse the clock on collagen loss",
    description: "Fine lines, wrinkles, firmness loss, skin laxity — the visible evidence of collagen production slowing. Whether you're in your 30s starting preventatively, your 40s addressing the first real signs, or your 50s-plus correcting years of sun and gravity, this is where our device-driven work lives. [RF microneedling](/services/rf-microneedling-facial), [Jet Plasma](/services/jet-plasma-facial), [Red Carpet Collagen](/services/red-carpet-collagen-facial), and our [Signature Facelift Facial](/services/essence-signature-facelift-facial) remodel skin from the inside out. Build your collagen framework back.",
    href: "/services/facial-treatments/anti-aging",
    image: { src: "/images/hubs/facial-treatments-hero.jpg", alt: "Anti-aging facial treatment session at Essence Medspa Chicago" },
  },
  {
    title: "Acne & Clarity Facials",
    tagline: "Break the breakout cycle",
    description: "Active acne, congestion, blackheads, oily skin, post-acne marks, hormonal flare-ups, teen acne, even bacne — all treatable, none of it permanent. Our [Acne Facial](/services/acne-facial) runs on a ZO Stimulator Peel and sulfur mask protocol with professional extractions. [Deep Pore Cleansing](/services/deep-pore-cleansing-facial) resets congested skin between visits. [Custom Facial](/services/custom-facial) handles mixed presentations, [Teen Facial](/services/teen-facial) meets adolescents where they are, and [Back Facial](/services/back-facial) addresses the breakouts nobody talks about. Clear skin is a protocol, not luck.",
    href: "/services/facial-treatments/acne-clarity",
    image: { src: "/images/categories/facial-treatments.jpg", alt: "Acne-clearing facial at Essence Medspa Chicago" },
  },
  {
    title: "Glow & Brightening Facials",
    tagline: "Radiance, restored",
    description: "Dull skin, dark spots, hyperpigmentation, uneven tone, melasma, post-inflammatory marks, summer sun damage — every tone, every season. Our [Brightening Facial](/services/brightening-facial) pairs professional-grade Vitamin C with algae patches and thermal organic clay. [Oxygen Facial](/services/oxygen-facial) and [Hydrofacial](/services/hydrofacial) deliver event-ready glow in 60 minutes. [Glutathione IV](/services/glutathione-brightening) brightens from the inside out — safe brightening for melanin-rich skin included. Essence already ranks page one for Vitamin C facials in Chicago; this is where that comes from.",
    href: "/services/facial-treatments/glow-brightening",
    image: { src: "/images/blog/benefits-of-vitamin-c-skin.jpg", alt: "Brightening facial at Essence Medspa Chicago" },
  },
];

export const localSignals = {
  eyebrow: "Chicago · Edgebrook",
  headline: "Built for Chicago skin. Rooted in Edgebrook for five-plus years.",
  body: "Essence Medspa sits at 6413 N Kinzua Ave, a short walk from Devon Avenue and the Edgebrook Metra stop on Chicago's Far Northwest Side. We've been here for more than five years — long enough to know which winters run brutally dry, which summers leave clients chasing pigmentation in September, and which heating-season weeks send rosacea and sensitivity flaring. This isn't a downtown chain pretending to know the neighborhood. Our clients walk, drive, or ride the Metra in, and most of them come back every four to six weeks.\n\nOur 4.9-star rating across 463 Google reviews reflects a client base pulled from across Edgebrook, Sauganash, Forest Glen, Lincolnwood, Park Ridge, Niles, and Norwood Park. For clients coming in from the suburbs or other North Side neighborhoods, we're easy to reach — a straight shot off I-94 and the Kennedy Expressway, with free onsite parking so you're never circling the block before an appointment. No downtown parking garage, no valet fees, no pre-treatment stress.\n\nChicago skin carries a specific set of concerns you won't find addressed on a generic national spa menu. Winters here are brutally dehydrating — forced-air heat, sub-zero wind, and months of low humidity strip the skin's barrier faster than any single bad product ever could. Summer flips the equation: humidity, sweat, and sebum congestion drive breakouts in clients who never break out the rest of the year. Post-summer appointments in September and October are some of our busiest, because that's when the sun damage, tan lines, and pigmentation from three months of lakefront sun actually surface.\n\nEvery protocol at Essence is built with those seasonal realities in mind. Winter brings more [hydrating facials](/services/hydrating-facial), [collagen-focused treatments](/services/red-carpet-collagen-facial), and barrier-repair home care. Summer shifts to [acne-clearing](/services/acne-facial) and [deep pore cleansing](/services/deep-pore-cleansing-facial). Fall is for pigment correction and [brightening](/services/brightening-facial). It's why our clients stay on a calendar — not a one-and-done cycle.",
};

export const teamSection = {
  eyebrow: "Your Aesthetician",
  headline: "Licensed hands. A decade-plus of Chicago skin.",
  body: "Every facial at Essence is performed by a State of Illinois licensed aesthetician — no exceptions, no entry-level techs running the treatment room. Our founder and lead aesthetician, Gosia, opened Essence after more than a decade in medical aesthetics, bringing advanced injectable certification and a results-first philosophy to every protocol on the menu. Our senior aesthetician (VERIFY WITH ESSENCE TEAM) specializes in facials, peels, and skin analysis — the quiet expertise of someone who has read thousands of skin presentations and can tell from across the room which products will and won't work for you.\n\nContinuing education is non-negotiable here. Our team actively trains in advanced modalities including RF microneedling, Jet Plasma, chemical peel calibration, and medical-grade product protocols. Aesthetics at Essence isn't a side hustle or a between-jobs career — it's a calling. That shows up in how every appointment starts: a real consultation, honest recommendations, and the confidence to tell you when an $85 [Teen Facial](/services/teen-facial) will outperform a $399 device treatment for your specific concern.",
  ctaHref: "/about",
};

export const pillarFaqs: FAQItem[] = [
  {
    question: "How often should I get a professional facial?",
    answer: "The short answer: every four to six weeks for most skin. That cadence matches your skin's natural cell turnover cycle of roughly 28 days — long enough for the previous treatment to fully integrate, short enough to keep momentum on results. If you're actively treating a concern like breakouts, pigmentation, or textural damage, you may benefit from treatments every three to four weeks for the first few sessions, then space them out as the skin stabilizes. Maintenance clients with healthy skin often do beautifully on a six-to-eight-week rhythm. Seasonal shifts matter too — Chicago winters leave most clients needing more hydration-focused visits, while post-summer appointments often skew toward [brightening](/services/brightening-facial) and pigment correction. For device-driven treatments like [RF microneedling](/services/rf-microneedling-facial), the spacing is different: three sessions four to six weeks apart, then maintenance every nine to twelve months. Your aesthetician will map out a personalized cadence at your first consultation — there's no universal number that applies to every skin.",
  },
  {
    question: "What's the difference between a facial and a chemical peel?",
    answer: "A facial is a full protocol — cleansing, exfoliation, extraction, treatment products, mask, massage, and finishing care across a 30 to 80 minute session. It works on multiple layers at once and balances results with relaxation. A chemical peel is a targeted exfoliation treatment using acids (glycolic, lactic, salicylic, TCA, or specialty blends) to accelerate cell turnover and address specific concerns like pigmentation, fine lines, acne, or textural damage. Peels can be part of a facial — our [Acne Facial](/services/acne-facial) uses a ZO Stimulator Peel, and our [Signature Facelift Peel](/services/essence-signature-facelift-peel) delivers organic four-layer exfoliation — or they can be done as a standalone 30-minute treatment via our [Custom Peel](/services/custom-peel). Peels deliver faster visible results for pigmentation and texture, but they also carry more aftercare responsibility: sun protection, no actives for several days, possible visible flaking. Facials deliver slower, gentler, more sustained improvement across multiple concerns at once. Your aesthetician will tell you honestly which approach suits your goals, skin type, and downtime tolerance.",
  },
  {
    question: "How do I choose the right facial for my skin type?",
    answer: "You don't have to — that's the job of your consultation. Every facial at Essence starts with a skin analysis by a licensed aesthetician who evaluates your skin type (oily, dry, combination, sensitive), current concerns (breakouts, dullness, fine lines, pigmentation, dehydration), seasonal state, lifestyle factors, and product history. From there, we match you to one of 21 treatments. Oily or breakout-prone skin typically starts with [Acne Facial](/services/acne-facial) or [Deep Pore Cleansing](/services/deep-pore-cleansing-facial). Dehydrated or sensitive skin leans toward [Hydrating Facial](/services/hydrating-facial) or [Oxygen Facial](/services/oxygen-facial). Dull or pigmented skin points toward our [Brightening Facial](/services/brightening-facial). Early aging concerns head toward [Signature Facelift Facial](/services/essence-signature-facelift-facial) or [Red Carpet Collagen](/services/red-carpet-collagen-facial). Advanced collagen loss opens the door to [RF microneedling](/services/rf-microneedling-facial) or [Jet Plasma](/services/jet-plasma-facial). When you genuinely can't decide or your presentation is mixed — oily T-zone with dry cheeks, breakouts alongside fine lines — our [Custom Facial](/services/custom-facial) is designed for exactly that: a fully personalized 50-minute treatment built after analysis. You're never locked into a wrong choice, and we'll never upsell you into a treatment your skin doesn't actually need.",
  },
  {
    question: "Are facials safe during pregnancy?",
    answer: "Many are, with modifications — but not all. Pregnancy-safe facials focus on gentle cleansing, hydration, enzyme exfoliation, massage, and soothing masks without retinoids, salicylic acid, hydroquinone, high-dose Vitamin A, or certain essential oils. Our [Hydrating Facial](/services/hydrating-facial) and [Oxygen Facial](/services/oxygen-facial) are well-suited to pregnancy and breastfeeding. What you should avoid during pregnancy: chemical peels with strong acids, retinoid-based treatments, [RF microneedling](/services/rf-microneedling-facial), [Jet Plasma](/services/jet-plasma-facial), high-percentage Vitamin C formulations, and any treatment involving electrical current or heat to the abdomen. Always tell your aesthetician you're pregnant or trying to conceive at booking — we'll pre-adjust the protocol, swap products for pregnancy-safe alternatives, and position you comfortably on the table (especially in the second and third trimesters). Pregnancy is actually one of the best times to stay consistent with facials: hormonal shifts drive melasma, breakouts, and sensitivity, and gentle professional care keeps those changes manageable. When in doubt, confirm with your OB before booking anything device-driven.",
  },
  {
    question: "Can I get a facial if I have active acne?",
    answer: "Yes — and you should. Active acne is one of the clearest reasons to book a professional facial rather than avoid one. Our [Acne Facial](/services/acne-facial) is specifically built for inflamed, breakout-prone skin: a ZO Stimulator Peel dissolves pore congestion from within, professional extractions safely clear existing comedones and pustules using sterile technique, and a sulfur mask calms inflammation while killing acne-causing bacteria. The critical detail most people miss is that picking at home — or getting a generic facial that aggravates sensitive acne-prone skin — causes more scarring and post-inflammatory marks than the acne itself. Professional extractions by a licensed aesthetician prevent scarring; we only extract lesions that are genuinely ready. For severe cystic or hormonal acne, we may layer in [Jet Plasma](/services/jet-plasma-facial) to address scarring once the active inflammation is controlled, or recommend a [Custom Peel](/services/custom-peel) series. Clients typically start on a three-to-four-week rhythm during active phases, then taper as the skin clears. Clear skin is a protocol — not luck, not genetics, and definitely not willpower.",
  },
  {
    question: "How much do medical-grade facials cost in Chicago?",
    answer: "Medical-grade facials in Chicago typically range from $95 at entry-level day spas to $400-plus at downtown medspas and plastic-surgery practices. At Essence Medspa in Edgebrook, our 21 facials span $59 to $399 with all prices published transparently — no surprise consultation fees, no upsell pressure, no pricing games at checkout. Entry-level treatments include [Microdermabrasion Neck](/services/microdermabrasion-neck) at $59 and [Collagen Sublime Eye Contour](/services/collagen-eye-contour) at $77. Mid-tier treatments like our [Teen Facial](/services/teen-facial) ($85), [Deep Pore Cleansing Facial](/services/deep-pore-cleansing-facial) ($125), [Acne Facial](/services/acne-facial) ($159), and [Hydrating Facial](/services/hydrating-facial) ($159) deliver serious protocol depth at accessible price points. Our [Custom Facial](/services/custom-facial) runs $169, [Signature Facelift Facial](/services/essence-signature-facelift-facial) is $195, [Red Carpet Collagen](/services/red-carpet-collagen-facial) is $215, and [Hydrofacial](/services/hydrofacial) is $229. Device-driven advanced treatments like [Jet Plasma](/services/jet-plasma-facial) ($350) and [RF Microneedling](/services/rf-microneedling-facial) ($399) sit at the top. Package pricing is available for series treatments — RF Microneedling, for instance, is $1,099 for three sessions, a meaningful savings for the three-session protocol we recommend. You'll always see pricing before booking.",
  },
  {
    question: "What should I do before a facial appointment?",
    answer: "Keep the prep simple. Stop using retinol, retinoids, AHAs, BHAs, and benzoyl peroxide for three to five days before any facial involving exfoliation, extraction, or chemical peels — these actives thin the skin barrier and can cause over-exfoliation or irritation during treatment. Avoid waxing the face for 48 hours prior. Arrive with clean skin if possible, though we'll cleanse thoroughly regardless. Skip heavy makeup, but don't stress if you came straight from work. Stay hydrated the day before — skin responds measurably better to every treatment when you're properly hydrated. Avoid alcohol the night before, especially before device-based treatments like [RF microneedling](/services/rf-microneedling-facial) or [Jet Plasma](/services/jet-plasma-facial), since alcohol dilates capillaries and increases post-treatment redness. If you're coming in for a peel, a device treatment, or anything with potential downtime, don't schedule it 48 hours before a major event — give your skin room to settle. Arrive 10 minutes early to complete your skin analysis form and consultation without feeling rushed.",
  },
  {
    question: "What should I avoid doing after a facial?",
    answer: "The 24 to 72 hours after a professional facial are when your skin is most receptive and most vulnerable. Avoid direct sun exposure and always wear mineral SPF 30+ — freshly exfoliated skin burns and pigments faster. Skip heat exposure: no hot yoga, saunas, steam rooms, or strenuous exercise for at least 24 hours (longer for peels and device treatments) since heat inflames freshly treated skin and can trigger post-inflammatory hyperpigmentation. Don't touch your face, don't pick, and don't apply makeup for at least six to eight hours after most facials — longer after extractions or peels. Pause active skincare ingredients like retinol, AHAs, BHAs, and benzoyl peroxide for three to five days to let the skin barrier rebuild. Avoid facial waxing, threading, and laser hair removal for at least a week. After [RF microneedling](/services/rf-microneedling-facial) or [Jet Plasma](/services/jet-plasma-facial), follow the specific aftercare protocol we send home with you — typically 48 hours of no heat, no actives, and mineral-based makeup only after the first 24 hours. Your aesthetician sends every client home with a written aftercare card tailored to the specific treatment.",
  },
  {
    question: "Are at-home facials as effective as professional ones?",
    answer: "No — and it's not close, though at-home care matters enormously as maintenance. The gap comes down to three things: product concentration, tools, and skin analysis. Medical-grade professional products used at Essence (ZO Skin Health, professional Vitamin C formulations, calibrated chemical peels) contain active ingredient concentrations that aren't available over the counter because they require licensed application to use safely. Tools matter equally: professional extractions performed by a trained aesthetician prevent scarring, while at-home picking almost guarantees it. [RF microneedling](/services/rf-microneedling-facial), [Jet Plasma](/services/jet-plasma-facial), [microdermabrasion](/services/microdermabrasion-facial), and device-driven treatments simply can't be replicated at home. Finally, skin analysis: a licensed aesthetician reads your skin — hydration, sebum, sensitivity, pigmentation history, barrier status — and matches protocol to presentation in ways even the best TikTok routine can't. That said, consistent at-home care between professional visits is what compounds results. We send every client home with a personalized home-care plan built around what works for your specific skin. The best routine is both: professional monthly-ish, at-home nightly.",
  },
  {
    question: "How long do facial results last?",
    answer: "It depends on the treatment and your home care. A single standard facial — [Hydrating](/services/hydrating-facial), [Brightening](/services/brightening-facial), [Custom](/services/custom-facial), [Oxygen](/services/oxygen-facial) — delivers an immediate glow that typically holds for two to four weeks before the skin cycles back to baseline. That's why most clients rebook every four to six weeks. Our [Signature Facelift Facial](/services/essence-signature-facelift-facial) and [Red Carpet Anti-Aging Facial](/services/red-carpet-anti-aging-facial) deliver visible lifting and smoothing that lasts roughly three to four weeks — ideal for pre-event bookings. Chemical peels ([Custom Peel](/services/custom-peel) and [Signature Facelift Peel](/services/essence-signature-facelift-peel)) show progressive results that build across a series of three to six treatments and can be maintained with one peel every six to eight weeks. Device-driven treatments deliver the longest-lasting outcomes: [RF microneedling](/services/rf-microneedling-facial) results build for eight to twelve weeks post-treatment and can last up to 12 months after a three-session series. [Jet Plasma](/services/jet-plasma-facial) shows similar progressive longevity. The universal rule: consistency beats intensity. Clients on a steady four-to-six-week rhythm see compounding improvement; one-off appointments deliver single-event glow.",
  },
  {
    question: "Can facials help with dark spots and hyperpigmentation?",
    answer: "Yes — and this is one of the areas where professional treatment dramatically outperforms anything you can do at home. Hyperpigmentation has multiple causes (sun damage, post-inflammatory marks from acne, melasma driven by hormones, post-procedure pigmentation), and each responds to different protocols. Our [Brightening Facial](/services/brightening-facial) uses professional-grade Vitamin C, algae patches, and thermal clay to inhibit melanin production and gradually even out tone — safe for every skin tone including melanin-rich skin. Progressive series of [Custom Peels](/services/custom-peel) at calibrated strengths accelerate cell turnover and fade darker marks over three to six treatments. [Meso Brightening](/services/meso-brightening) delivers brightening ingredients deeper into the dermis for stubborn pigmentation that surface treatments can't reach. [Glutathione Brightening](/services/glutathione-brightening) works from the inside out via IV infusion — popular among clients addressing melasma and overall brightening. For post-acne marks specifically, pairing [Acne Facial](/services/acne-facial) with [Jet Plasma](/services/jet-plasma-facial) once the active acne clears delivers particularly strong results. Sun protection is non-negotiable throughout any brightening protocol — without daily SPF, pigmentation returns.",
  },
  {
    question: "At what age should I start getting facials?",
    answer: "Earlier than most people think, and for different reasons at each stage. Teens 13 to 19 benefit from our [Teen Facial](/services/teen-facial) — designed specifically for adolescent skin, hormonal breakouts, and the habit-forming stage when young clients are learning what products actually work for their skin. Your 20s are the ideal preventative decade: monthly-ish [Custom Facials](/services/custom-facial) or [Hydrofacials](/services/hydrofacial), consistent SPF, and early Vitamin C use via [Brightening Facials](/services/brightening-facial) to protect against sun damage before it surfaces. Your 30s are when most clients start seeing the first real signs of collagen loss — this is when preventative [RF microneedling](/services/rf-microneedling-facial) or [Signature Facelift Facial](/services/essence-signature-facelift-facial) series deliver the biggest long-term return. Your 40s shift to active correction: deeper peels, more consistent device work, [Red Carpet Collagen](/services/red-carpet-collagen-facial) for visible anti-aging. Your 50s and beyond focus on maintenance, skin tightening, and pigment correction — [Jet Plasma](/services/jet-plasma-facial) and RF microneedling become cornerstone treatments. There's no age floor and no age ceiling — we've treated clients in their teens and clients in their 70s in the same week. What changes is the protocol, not the outcome: healthier, clearer, more resilient skin at every decade.",
  },
];
