// src/content/services/4d-face-lifting-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "4D Face Lifting Massage Chicago | $195 | Essence Medspa", description: "4D Face Lifting Massage at Essence Medspa Chicago. 60-minute non-invasive face lifting combining Eastern and modern techniques. $195.", keywords: ["4d face lifting massage Chicago", "4d face lifting massage near me"], canonical: "https://www.essence-medspa.com/services/4d-face-lifting-massage" },
  hero: { eyebrow: "Facial Treatments", headline: "Non-Invasive Lift Meets Ancient Technique", subheadline: "A 60-minute multi-layer face lifting treatment combining Eastern wisdom with modern skincare science. Targets multiple tissue layers for comprehensive lifting.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$195 · 60 minutes", image: { src: "/images/services/4d-face-lifting-massage-hero.jpg", alt: "Non-Invasive Lift Meets Ancient Technique at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "A 60-minute multi-layer face lifting treatment combining Eastern wisdom with modern skincare science. Targets multiple tissue layers for comprehensive lifting. This professional treatment is performed by our licensed aestheticians using medical-grade products selected for maximum efficacy.\n\nEvery session begins with a skin assessment to ensure the treatment is tailored to your current skin condition and concerns.", keyFacts: [{ label: "Treatment Time", value: "60 minutes" }, { label: "Downtime", value: "None to minimal" }, { label: "Price", value: "$195" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Facial Sagging", description: "Multi-layer massage technique lifts and repositions soft tissue for visible contouring." }, { area: "Loss of Definition", description: "Targeted muscle work restores jawline, cheekbone, and brow definition." }, { area: "Lymphatic Congestion", description: "Drainage techniques reduce puffiness and improve overall facial contour." }, { area: "Tension-Related Aging", description: "Releasing facial muscle tension prevents deepening of expression lines." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Assessment", description: "Your aesthetician evaluates your skin and confirms the treatment plan." }, { step: "02", title: "Preparation", description: "Thorough cleansing and prep to maximize treatment effectiveness." }, { step: "03", title: "Active Treatment", description: "The core treatment protocol is applied with expert technique and professional products." }, { step: "04", title: "Finishing", description: "Protective finishing products and aftercare instructions to maintain your results." }] },
  faqs: [
    { question: "How often should I get this treatment?", answer: "Every 4–6 weeks for maintained results. Your aesthetician will recommend the ideal frequency for your skin." },
    { question: "Is there any downtime?", answer: "Most facial treatments have minimal to no downtime. Your aesthetician will advise on any specific post-treatment care." },
    { question: "Can this be combined with other treatments?", answer: "Many treatments complement each other well. Ask your aesthetician about combination protocols during your visit." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Custom Facial", slug: "custom-facial", tagline: "Fully personalized treatment" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "Device-driven cleansing and glow" }] },
  finalCTA: { headline: "Ready for Beautiful Skin?", subheadline: "Book your treatment today. Expert care, visible results.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};