// src/content/services/acne-facial.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Acne Facial Chicago | Clear Breakouts | $159 | Essence Medspa", description: "Professional acne facial at Essence Medspa Chicago. 50-minute treatment with ZO Stimulator Peel and sulfur mask to clear breakouts and calm inflammation. $159.", keywords: ["acne facial Chicago", "acne treatment near me", "facial for breakouts Edgebrook"], canonical: "https://www.essence-medspa.com/services/acne-facial" },
  hero: { eyebrow: "Facial Treatments", headline: "Clear Breakouts. Calm Inflammation. Restore Confidence.", subheadline: "Our 50-minute Acne Facial combines clinical-grade products with expert extraction to clear active breakouts, reduce inflammation, and start healing acne scarring — all in one targeted session.", primaryCTA: { text: "Book Acne Facial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$159 · 50 minutes", image: { src: "/images/services/acne-facial-hero.jpg", alt: "Professional acne facial treatment at Essence Medspa Chicago" } },
  overview: { headline: "What Is Our Acne Facial?", body: "Our Acne Facial is a 50-minute clinical treatment specifically designed for breakout-prone skin. It begins with a deep cleanse and skin analysis, followed by a ZO Stimulator Peel that penetrates pores to dissolve congestion from within. Professional extractions remove existing comedones and pustules safely.\n\nA sulfur-based mask draws out remaining impurities while calming inflammation and killing acne-causing bacteria. The treatment finishes with a soothing, oil-free moisturizer and SPF. Unlike generic facials that might aggravate acne, every product and technique in this facial is chosen specifically for breakout-prone skin.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Key Ingredients", value: "ZO Stimulator Peel, Sulfur Mask" }, { label: "Downtime", value: "Minimal (mild redness)" }, { label: "Price", value: "$159" }, { label: "Frequency", value: "Every 3–4 weeks" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Active Breakouts", description: "Professional extraction and antibacterial treatment clear existing pimples, cysts, and congestion." }, { area: "Clogged Pores", description: "ZO Stimulator Peel dissolves the debris inside pores that leads to future breakouts." }, { area: "Inflammation & Redness", description: "Sulfur mask calms inflamed skin and reduces the redness around active lesions." }, { area: "Post-Acne Marks", description: "The peel accelerates cell turnover, helping fade post-inflammatory marks with each session." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Deep Cleanse & Analysis", description: "Thorough double cleanse and skin assessment to identify your acne type and severity." }, { step: "02", title: "ZO Stimulator Peel", description: "Clinical-grade peel penetrates pores, dissolving congestion and prepping skin for extraction." }, { step: "03", title: "Professional Extractions", description: "Gentle, thorough extraction of comedones and pustules using proper technique to prevent scarring." }, { step: "04", title: "Sulfur Mask & Finish", description: "Antibacterial sulfur mask calms inflammation. Finished with oil-free hydration and SPF protection." }] },
  faqs: [
    { question: "Will the extractions leave scars?", answer: "Professional extraction by a trained aesthetician actually prevents scarring — unlike picking at home. We use proper technique, sterile tools, and only extract lesions that are ready." },
    { question: "How often should I get an Acne Facial?", answer: "Every 3–4 weeks during active breakout phases. As your skin clears, we can space sessions further apart or transition to a maintenance facial." },
    { question: "Can I wear makeup after?", answer: "We recommend waiting 6–8 hours to let the treatment absorb. Mineral makeup is okay the next day. Your aesthetician will provide specific aftercare instructions." },
    { question: "Is this facial good for cystic acne?", answer: "Yes — the sulfur mask and ZO Peel are particularly effective for deep, cystic breakouts. For severe cystic acne, we may recommend combining this facial with other treatments in a series." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Deep Pore Cleansing", slug: "deep-pore-cleansing-facial", tagline: "Intensive pore detox between acne facials" }, { name: "Custom Peel", slug: "custom-peel", tagline: "Stronger exfoliation for stubborn acne" }, { name: "Jet Plasma Facial", slug: "jet-plasma-facial", tagline: "Address scarring once acne is controlled" }] },
  finalCTA: { headline: "Ready to Clear Your Skin?", subheadline: "Book an Acne Facial. Clinical-grade treatment for real results.", primaryCTA: { text: "Book Acne Facial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};