// src/content/services/athletes-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Athletes Massage Chicago | $126–$165 | Essence Medspa", description: "Built for Active Bodies 50 or 80-minute sports-focused massage combining deep tissue, stretching, and targeted muscle group ... At Essence Medspa Chicago. $126–$165.", keywords: ["athletes massage Chicago", "athletes massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/athletes-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Built for Active Bodies", subheadline: "50 or 80-minute sports-focused massage combining deep tissue, stretching, and targeted muscle group work. Performance recovery for serious athletes and weekend warriors.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$126–$165", image: { src: "/images/services/athletes-massage-hero.jpg", alt: "Built for Active Bodies at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50 or 80-minute sports-focused massage combining deep tissue, stretching, and targeted muscle group work. Performance recovery for serious athletes and weekend warriors.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$126–$165" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Post-Workout Recovery", description: "Targeted work on muscles used in your sport flushes lactic acid and reduces delayed-onset soreness." }, { area: "Flexibility & Range of Motion", description: "Assisted stretching and myofascial release improve mobility and reduce injury risk." }, { area: "Sports-Specific Tension", description: "Tell us your sport and we'll focus on the muscle groups that take the most strain." }, { area: "Performance Maintenance", description: "Regular sports massage keeps muscles supple, prevents compensatory patterns, and supports training longevity." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};