// src/content/services/back-facial.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Back Facial Chicago | $179 | Essence Medspa", description: "Back facial at Essence Medspa Chicago. 50-minute deep cleansing treatment for back acne and blemishes. $179.", keywords: ["back facial Chicago", "back facial near me"], canonical: "https://www.essence-medspa.com/services/back-facial" },
  hero: { eyebrow: "Body Treatments", headline: "Clear, Smooth, Blemish-Free Back Skin", subheadline: "50-minute deep cleansing back facial with sulfur mask and peel. Targets back acne, blemishes, and congestion — because your back deserves professional care too.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$179 · 50 minutes", image: { src: "/images/services/back-facial-hero.jpg", alt: "Clear, Smooth, Blemish-Free Back Skin at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "50-minute deep cleansing back facial with sulfur mask and peel. Targets back acne, blemishes, and congestion — because your back deserves professional care too.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$179" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Back Acne (“Bacne”)", description: "Professional extraction and antibacterial sulfur mask clear breakouts on the back." }, { area: "Blemishes & Scarring", description: "Peel component accelerates cell turnover to fade post-inflammatory marks." }, { area: "Congestion", description: "Deep cleansing reaches areas you can't properly care for at home." }, { area: "Pre-Event Prep", description: "Get your back wedding-ready, vacation-ready, or just smooth and clear." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};