// src/content/services/back-microdermabrasion.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Back Microdermabrasion Chicago | $115 | Essence Medspa", description: "Back microdermabrasion at Essence Medspa Chicago. 50-minute crystal exfoliation for smooth, refined back skin. $115.", keywords: ["back microdermabrasion Chicago", "back microdermabrasion near me"], canonical: "https://www.essence-medspa.com/services/back-microdermabrasion" },
  hero: { eyebrow: "Body Treatments", headline: "Crystal Exfoliation for the Back", subheadline: "50-minute back crystal exfoliation to smooth, refine, and renew back skin. Removes dead cells for a softer, more refined texture.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$115 · 50 minutes", image: { src: "/images/services/back-microdermabrasion-hero.jpg", alt: "Crystal Exfoliation for the Back at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "50-minute back crystal exfoliation to smooth, refine, and renew back skin. Removes dead cells for a softer, more refined texture.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$115" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Rough Texture", description: "Crystal exfoliation mechanically removes the buildup of dead cells for silky-smooth back skin." }, { area: "Uneven Tone", description: "Removes discolored surface cells for more uniform back skin." }, { area: "Light Scarring", description: "Progressive treatments smooth shallow scarring and textural irregularities." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};