// src/content/services/back-stimulator-peel.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Back Stimulator Peel Chicago | $149 | Essence Medspa", description: "Back Stimulator Peel at Essence Medspa Chicago. 30-minute no-downtime back peel for sun damage and spots. $149.", keywords: ["back stimulator peel Chicago", "back stimulator peel near me"], canonical: "https://www.essence-medspa.com/services/back-stimulator-peel" },
  hero: { eyebrow: "Body Treatments", headline: "Peel Away Sun Damage and Spots", subheadline: "30-minute no-downtime back peel for sun damage, age spots, and uneven tone. Stimulates healthy cell growth without harsh recovery.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$149 · 30 minutes", image: { src: "/images/services/back-stimulator-peel-hero.jpg", alt: "Peel Away Sun Damage and Spots at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "30-minute no-downtime back peel for sun damage, age spots, and uneven tone. Stimulates healthy cell growth without harsh recovery.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "30 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$149" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Back Sun Damage", description: "Chemical exfoliation removes sun-damaged cells from the back and shoulders." }, { area: "Age Spots", description: "Accelerated cell turnover lifts pigmented spots over a series of treatments." }, { area: "Uneven Back Tone", description: "Progressive peeling reveals more even-toned skin beneath." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};