// src/content/services/bamboo-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Bamboo Massage Chicago | $125–$165 | Essence Medspa", description: "Warm Bamboo, Deep Relaxation 50 or 80-minute massage using warm bamboo rods for tension relief and deep relaxation. A unique sens... At Essence Medspa Chicago. $125–$165.", keywords: ["bamboo massage Chicago", "bamboo massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/bamboo-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Warm Bamboo, Deep Relaxation", subheadline: "50 or 80-minute massage using warm bamboo rods for tension relief and deep relaxation. A unique sensory experience that combines pressure and warmth.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$125–$165", image: { src: "/images/services/bamboo-massage-hero.jpg", alt: "Warm Bamboo, Deep Relaxation at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50 or 80-minute massage using warm bamboo rods for tension relief and deep relaxation. A unique sensory experience that combines pressure and warmth.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$125–$165" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Broad Muscle Groups", description: "Bamboo rods cover more surface area than hands, efficiently releasing tension in large muscle groups." }, { area: "Digital Fatigue", description: "The organic, natural quality of bamboo creates a grounding “digital detox” experience." }, { area: "General Tension", description: "Warm bamboo glides along muscles, releasing tension with a unique rolling pressure." }, { area: "Stress", description: "The combination of warmth, rhythm, and natural materials creates deep mental relaxation." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};