// src/content/services/body-scrub.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Body Scrub Chicago | $189 | Essence Medspa", description: "Body scrub at Essence Medspa Chicago. 85-minute Royal Fijian Ritual with organic sugar, honey, hot stones, coconut milk. $189.", keywords: ["body scrub Chicago", "body scrub near me"], canonical: "https://www.essence-medspa.com/services/body-scrub" },
  hero: { eyebrow: "Body Treatments", headline: "The Royal Fijian Ritual", subheadline: "85-minute full-body luxury treatment with organic cane sugar, honey masque, hot stones, and coconut milk wrap. A head-to-toe sensory experience.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$189 · 85 minutes", image: { src: "/images/services/body-scrub-hero.jpg", alt: "The Royal Fijian Ritual at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "85-minute full-body luxury treatment with organic cane sugar, honey masque, hot stones, and coconut milk wrap. A head-to-toe sensory experience.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "85 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$189" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Dry, Rough Skin", description: "Organic cane sugar exfoliation removes dead cells from head to toe for silky-smooth skin." }, { area: "Poor Circulation", description: "Hot stones and massage techniques boost blood flow and lymphatic drainage." }, { area: "Dull Body Skin", description: "The honey masque and coconut milk wrap nourish and brighten the entire body." }, { area: "Stress & Tension", description: "85 minutes of full-body attention is deeply relaxing — this is a treatment and a retreat." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};