// src/content/services/brightening-facial.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Brightening Facial Chicago | Vitamin C Antioxidant | $155 | Essence Medspa", description: "Brightening facial with Vitamin C at Essence Medspa Chicago. 50-minute antioxidant treatment with algae patches and thermal clay for luminous, radiant skin. $155.", keywords: ["brightening facial Chicago", "Vitamin C facial near me", "brightening treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/brightening-facial" },
  hero: { eyebrow: "Facial Treatments", headline: "Vitamin C-Powered Radiance", subheadline: "Our 50-minute Brightening Facial uses concentrated Vitamin C, algae patches, and thermal organic clay to brighten dull skin, protect against environmental damage, and restore luminous radiance.", primaryCTA: { text: "Book Brightening Facial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$155 · 50 minutes", image: { src: "/images/services/brightening-facial-hero.jpg", alt: "Brightening Vitamin C facial treatment at Essence Medspa Chicago" } },
  overview: { headline: "What Is Our Brightening Facial?", body: "The Brightening Facial is a 50-minute antioxidant treatment centered around professional-grade Vitamin C — one of the most proven brightening and anti-aging ingredients in skincare. The treatment begins with a gentle enzyme exfoliation to remove the dull surface layer, followed by application of concentrated Vitamin C serum.\n\nAlgae patches deliver deep hydration and minerals while thermal organic clay draws out toxins and tightens pores. The combination brightens existing discoloration, protects against future damage from UV and pollution, and stimulates collagen production for progressive improvement.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Key Ingredients", value: "Vitamin C, Algae, Thermal Clay" }, { label: "Downtime", value: "None" }, { label: "Price", value: "$155" }, { label: "Ideal For", value: "Dull skin, uneven tone, prevention" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Dull, Lackluster Skin", description: "Vitamin C and exfoliation reveal fresh, bright skin beneath the tired surface layer." }, { area: "Uneven Skin Tone", description: "Vitamin C inhibits melanin production, gradually evening out light discoloration." }, { area: "Environmental Damage", description: "Antioxidant protection neutralizes free radicals from UV exposure, pollution, and screen time." }, { area: "Early Signs of Aging", description: "Vitamin C stimulates collagen production — making this an excellent preventive treatment for younger clients." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Gentle Exfoliation", description: "Enzyme exfoliation removes the dull outer layer without irritation." }, { step: "02", title: "Vitamin C Infusion", description: "Professional-grade Vitamin C serum applied and massaged into freshly exfoliated skin." }, { step: "03", title: "Algae Patches + Thermal Clay", description: "Algae patches deliver minerals while thermal clay purifies and tightens." }, { step: "04", title: "Finishing Protection", description: "Hydrating moisturizer and SPF lock in brightness and protect your glow." }] },
  faqs: [
    { question: "Is the Brightening Facial good for sensitive skin?", answer: "Yes — Vitamin C is generally well-tolerated even by sensitive skin. We use a professional formulation at the right pH for efficacy without irritation." },
    { question: "How quickly will I see results?", answer: "Immediate brightness after one session. For deeper discoloration or uneven tone, a series of 3–4 treatments spaced 3–4 weeks apart produces more dramatic results." },
    { question: "Can I do this facial year-round?", answer: "Absolutely. Vitamin C actually provides some photoprotection, making it ideal for all seasons. In Chicago, it's particularly valuable in winter when skin tends to look dullest." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Glutathione Brightening", slug: "glutathione-brightening", tagline: "Internal brightening for inside-out radiance" }, { name: "Meso Brightening", slug: "meso-brightening", tagline: "Deeper brightening for stubborn pigmentation" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "Deep cleansing before brightening" }] },
  finalCTA: { headline: "Ready to Brighten Up?", subheadline: "Book a Brightening Facial. Immediate radiance, zero downtime.", primaryCTA: { text: "Book Brightening Facial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};