// src/content/services/collagen-eye-contour.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Collagen Eye Contour Chicago | Under Eye Treatment | $77 | Essence Medspa", description: "Collagen Sublime Eye Contour at Essence Medspa Chicago. 30-minute 4-step eye treatment for under-eye revitalization and anti-aging. Just $77.", keywords: ["eye contour treatment Chicago", "under eye facial near me", "collagen eye treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/collagen-eye-contour" },
  hero: { eyebrow: "Facial Treatments", headline: "Revitalize the Delicate Eye Area", subheadline: "A 30-minute, 4-step professional eye treatment that nourishes, firms, and revitalizes the under-eye area. The perfect entry point to eye care — or monthly maintenance between advanced treatments.", primaryCTA: { text: "Book Eye Contour", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$77 · 30 minutes · 4 Steps", image: { src: "/images/services/eye-contour-hero.jpg", alt: "Collagen eye contour treatment at Essence Medspa Chicago" } },
  overview: { headline: "What Is the Collagen Eye Contour?", body: "The Collagen Sublime Eye Contour is a targeted 30-minute treatment specifically designed for the thin, delicate skin around your eyes. The 4-step protocol includes gentle cleansing, a collagen-infused eye mask, peptide serum application, and a hydrating eye cream finish.\n\nAt $77, it's our most accessible professional eye treatment — ideal as a standalone refresher, an add-on to any facial, or a monthly maintenance treatment between PRF or PRP under-eye sessions.", keyFacts: [{ label: "Treatment Time", value: "30 minutes" }, { label: "Steps", value: "4-step protocol" }, { label: "Downtime", value: "None" }, { label: "Price", value: "$77" }, { label: "Ideal For", value: "Maintenance, dark circles, fine lines" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Dark Circles", description: "Collagen and peptide infusion brightens the under-eye area and reduces shadow appearance." }, { area: "Fine Lines", description: "Hydrating ingredients plump the thin eye area skin, softening crow's feet and under-eye creases." }, { area: "Puffiness", description: "Cooling application reduces fluid retention and puffiness around the eye." }, { area: "Dryness", description: "Deep hydration addresses the chronic dryness common in the eye area, especially in Chicago's dry winters." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Gentle Cleanse", description: "Eye-safe cleanser removes makeup and debris from the delicate periorbital area." }, { step: "02", title: "Collagen Eye Mask", description: "Professional collagen-infused patches applied under the eyes to deliver concentrated nourishment." }, { step: "03", title: "Peptide Serum", description: "Anti-aging peptide serum massaged around the eye area with gentle pressure techniques." }, { step: "04", title: "Hydrating Finish", description: "Rich eye cream seals in the active ingredients and provides lasting hydration." }] },
  faqs: [
    { question: "Can I add this to another facial?", answer: "Absolutely — it's one of our most popular add-ons. Adding the Eye Contour to any full facial takes just 15 extra minutes." },
    { question: "How often should I get this treatment?", answer: "Monthly for maintenance. It's an excellent bridge between more intensive treatments like PRF Under Eyes." },
    { question: "Is it good for mature skin around the eyes?", answer: "Yes — the collagen and peptide ingredients specifically target age-related thinning, dryness, and loss of elasticity in the eye area." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "PRF Under Eyes", slug: "prf-under-eyes", tagline: "Advanced regeneration for deeper concerns" }, { name: "Custom Facial", slug: "custom-facial", tagline: "Add Eye Contour to any full facial" }, { name: "Brightening Facial", slug: "brightening-facial", tagline: "Full-face brightness plus eye treatment" }] },
  finalCTA: { headline: "Give Your Eyes the Attention They Deserve", subheadline: "Book a Collagen Eye Contour. 30 minutes, $77, immediate results.", primaryCTA: { text: "Book Eye Contour", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};