// src/content/services/collagen-induction-therapy.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Collagen Induction Therapy + Vitamin C | $350 | Essence Medspa Chicago", description: "Microneedling with Vitamin C at Essence Medspa Chicago. Boost collagen, improve radiance, and rejuvenate skin. $350. Free consultation at our Edgebrook studio.", keywords: ["collagen induction therapy Chicago", "microneedling Vitamin C near me", "collagen boost facial Edgebrook"], canonical: "https://www.essence-medspa.com/services/collagen-induction-therapy" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Rebuild Your Skin's Foundation from Within", subheadline: "Collagen Induction Therapy combines professional micro-needling with concentrated Vitamin C to stimulate deep collagen production, brighten skin, and restore a youthful, firm complexion.", primaryCTA: { text: "Book Your Collagen Induction Session", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$350 · 45–60 min · Free Consultation", image: { src: "/images/services/collagen-induction-hero.jpg", alt: "Collagen induction therapy micro-needling treatment at Essence Medspa" }, stats: [{ value: "45–60", suffix: " min", label: "Treatment Time" }, { value: "2–4", label: "Weeks to Visible Results" }, { value: "3–4", label: "Sessions for Best Outcome" }] },
  overview: { headline: "What Is Collagen Induction Therapy?", body: "Collagen Induction Therapy uses a professional micro-needling device to create thousands of controlled micro-channels in the skin. These micro-injuries trigger your body's natural wound-healing response, which produces new collagen and elastin fibers.\n\nThe addition of concentrated Vitamin C serum takes this further. As the micro-channels close, they draw the Vitamin C deep into the skin where it acts as a powerful antioxidant, brightening agent, and collagen co-factor — amplifying the regenerative effect. The result is firmer, brighter, more resilient skin that improves progressively over the following weeks.", keyFacts: [{ label: "Treatment Time", value: "45–60 minutes" }, { label: "Results Timeline", value: "2–4 weeks (progressive)" }, { label: "Results Last", value: "3–6 months per session" }, { label: "Downtime", value: "1–2 days redness" }, { label: "Price", value: "$350" }, { label: "Sessions Recommended", value: "3–4 for optimal results" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Fine Lines & Wrinkles", description: "New collagen fills lines from beneath the surface, creating smoother, plumper skin over time." }, { area: "Dull, Tired Skin", description: "Vitamin C brightens and protects while accelerated cell turnover reveals fresh, luminous skin." }, { area: "Large Pores", description: "Collagen production around pore walls tightens and minimizes their appearance." }, { area: "Mild Scarring", description: "Controlled micro-injuries and collagen remodeling gradually fill shallow acne scars." }, { area: "Sun Damage", description: "Vitamin C inhibits melanin production while new skin cells replace sun-damaged surface layers." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Skin Cleansing & Prep", description: "Your face is thoroughly cleansed and prepped. Topical numbing cream is applied for comfort." }, { step: "02", title: "Micro-Needling", description: "A professional micro-needling device creates controlled micro-channels across the treatment areas at a depth calibrated to your skin's needs." }, { step: "03", title: "Vitamin C Infusion", description: "Concentrated Vitamin C serum is applied and driven deep into the skin through the open micro-channels for maximum penetration." }, { step: "04", title: "Recovery Mask & Aftercare", description: "A soothing recovery mask calms the skin. Mild redness subsides within 1–2 days. Collagen production accelerates over the following weeks." }] },
  faqs: [
    { question: "How is this different from regular micro-needling?", answer: "The addition of professional-grade Vitamin C serum significantly amplifies the results. Vitamin C is a collagen co-factor (your body needs it to produce collagen) and a powerful brightening agent. Infusing it through open micro-channels delivers it deeper than any topical application." },
    { question: "Can I do this treatment in summer?", answer: "Yes, but strict sun protection is essential for 2 weeks afterward. Vitamin C actually provides some photoprotection, but we recommend SPF 50 daily and avoiding direct sun exposure." },
    { question: "How many sessions do I need?", answer: "You'll see improvement after one session, but 3–4 sessions spaced 4–6 weeks apart produce the most dramatic collagen rebuilding. After that, maintenance once every 3–6 months." },
    { question: "Is it painful?", answer: "With topical numbing cream, most clients describe the sensation as mild prickling. Comfort levels are excellent and the treatment is well-tolerated." },
  ],
  pricing: { headline: "Collagen Induction Therapy Pricing", tiers: [{ name: "Single Session", price: "$350", description: "One complete Collagen Induction Therapy session with numbing, microneedling, Vitamin C infusion, and recovery mask.", includes: ["Free consultation", "Numbing cream", "Professional Vitamin C serum infusion", "Recovery mask + aftercare guidance"] }, { name: "3-Session Protocol", price: "$950", description: "The recommended 3-session protocol for meaningful collagen rebuilding, scar reduction, and skin firming. Sessions spaced 4–6 weeks apart.", includes: ["Three full sessions", "Free consultation", "Customized depth settings per session", "Progressive results tracking"], popular: true }], disclaimer: "No hidden fees. Exact session count confirmed at free consultation." },
  results: { headline: "Collagen Induction Therapy by the Numbers", stats: [{ value: "463", suffix: "+", label: "5-Star Google Reviews" }, { value: "2–4", label: "Weeks to Visible Results" }, { value: "3–6", label: "Months Results Last" }, { value: "1–2", label: "Days of Downtime" }] },
  idealCandidates: { headline: "Is Collagen Induction Therapy Right for You?", good: ["You want to brighten dull skin while simultaneously building collagen", "You have shallow acne scars or large pores you want progressively improved", "You're looking for a microneedling treatment enhanced with a collagen-boosting active", "You want gradual, natural-looking improvement that builds over weeks", "You're 25+ and starting a proactive anti-aging collagen maintenance protocol", "You want Vitamin C driven deeper than any at-home serum can reach"], alternatives: [{ concern: "Significant skin laxity or deep wrinkles requiring structural remodeling", recommendation: "RF Microneedling adds radiofrequency energy to the microneedling process for deeper collagen contraction and tightening" }, { concern: "Looking for the most advanced growth factor protocol for scarring", recommendation: "PRF Facial or PRP Facial adds autologous growth factors for enhanced regeneration" }, { concern: "Primarily focused on brightening and surface glow without needling", recommendation: "The Brightening Facial or Oxygen Facial delivers Vitamin C results without the microneedling component" }] },
  relatedServices: { headline: "Often Combined With", items: [{ name: "PRP Facial", slug: "prp-facial", tagline: "Add growth factors for enhanced collagen production" }, { name: "RF Microneedling", slug: "rf-microneedling-facial", tagline: "Upgrade to radiofrequency for deeper tightening and scar correction" }, { name: "Brightening Facial", slug: "brightening-facial", tagline: "Maintain radiance between collagen induction sessions" }, { name: "Custom Peel", slug: "custom-peel", tagline: "Exfoliate before microneedling for deeper serum penetration" }] },
  finalCTA: { headline: "Ready to Rebuild Your Collagen?", subheadline: "Book your Collagen Induction Therapy at Essence Medspa. Visible improvement after the first session, significant results after the full protocol — free consultation included, no commitment required.", primaryCTA: { text: "Book Your Collagen Induction Session", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
