// src/content/services/couples-wine-platter.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Share Something Special | $80 for 2 guests | Essence Medspa Chicago", description: "Wine and artisan platter for two in the Oasis Lounge. Seasonal fruits, imported cheeses, artisan chocolates, and wine — the perfect addition to any couples massage or treatment. $80 for 2 guests at Essence Medspa Chicago.", keywords: ["spa upgrade Chicago", "couples wine platter", "private spa suite Edgebrook"], canonical: "https://www.essence-medspa.com/services/couples-wine-platter" },
  hero: { eyebrow: "Spa Upgrades", headline: "Share Something Special", subheadline: "Wine and artisan platter for two in the Oasis Lounge. Seasonal fruits, imported cheeses, artisan chocolates, and wine — the perfect addition to any couples massage or treatment.", primaryCTA: { text: "Book with Upgrade", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$80 for 2 guests", image: { src: "/images/services/couples-wine-platter-hero.jpg", alt: "Share Something Special at Essence Medspa Chicago" } },
  overview: { headline: "About This Upgrade", body: "Wine and artisan platter for two in the Oasis Lounge. Seasonal fruits, imported cheeses, artisan chocolates, and wine — the perfect addition to any couples massage or treatment.\n\nThis upgrade can be added to any treatment at Essence Medspa. Simply mention it when booking online or over the phone, and we'll have everything prepared for your arrival.", keyFacts: [{ label: "Price", value: "$80 for 2 guests" }, { label: "Add to", value: "Any treatment" }] },
  benefits: { headline: "What's Included", items: [{ area: "Premium Experience", description: "Elevate any standard treatment into something truly special and memorable." }, { area: "Perfect for Occasions", description: "Birthdays, anniversaries, date nights, bachelorette parties, or just because you deserve it." }] },
  process: { headline: "How It Works", steps: [{ step: "01", title: "Book Your Treatment", description: "Choose any treatment from our menu and add this upgrade." }, { step: "02", title: "Arrive & Enjoy", description: "Everything is prepared before you arrive. Just walk in and relax." }] },
  faqs: [
    { question: "Can I add this upgrade to any treatment?", answer: "Yes — any facial, massage, body treatment, or advanced aesthetic service can be enhanced with this upgrade." },
    { question: "Do I need to book in advance?", answer: "We recommend adding upgrades when you book to ensure availability, but we can sometimes accommodate day-of requests." },
  ],
  relatedServices: { headline: "Popular Treatments to Upgrade", items: [{ name: "Couples Swedish Massage", slug: "couples-swedish-massage", tagline: "The most popular couples treatment" }, { name: "Custom Facial", slug: "custom-facial", tagline: "Personalized facial + private suite" }, { name: "Deep Tissue Massage", slug: "deep-tissue-massage", tagline: "Intensive relief in a premium setting" }] },
  finalCTA: { headline: "Make Your Visit Unforgettable", subheadline: "Add this upgrade when booking. We'll handle the rest.", primaryCTA: { text: "Book with Upgrade", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};