// src/content/services/couples-deep-tissue-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Couples Deep Tissue Massage Chicago | $438 | Essence Medspa", description: "Deep Relief, Together 80-minute couples deep tissue massage in the Bamboo Suite with wine and platter included. Our most c... At Essence Medspa Chicago. $438.", keywords: ["couples deep tissue massage Chicago", "couples deep tissue massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/couples-deep-tissue-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Deep Relief, Together", subheadline: "80-minute couples deep tissue massage in the Bamboo Suite with wine and platter included. Our most comprehensive couples experience.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$438", image: { src: "/images/services/couples-deep-tissue-massage-hero.jpg", alt: "Deep Relief, Together at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "80-minute couples deep tissue massage in the Bamboo Suite with wine and platter included. Our most comprehensive couples experience.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$438" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Couples Deep Tissue", description: "80 minutes of deep tissue massage for both partners — serious relief for serious tension." }, { area: "Full Bamboo Suite + Refreshments", description: "Wine and artisan platter included in the Oasis Lounge before or after your treatment." }, { area: "Complete Experience", description: "The longest and most comprehensive couples offering — 80 minutes of treatment plus lounge time." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};