// src/content/services/couples-swedish-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Couples Swedish Massage Chicago | $318 | Essence Medspa", description: "Share Relaxation, Side by Side 50-minute couples Swedish massage in our private Bamboo Suite. Wine and cheese platter upgrade avail... At Essence Medspa Chicago. $318.", keywords: ["couples swedish massage Chicago", "couples swedish massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/couples-swedish-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Share Relaxation, Side by Side", subheadline: "50-minute couples Swedish massage in our private Bamboo Suite. Wine and cheese platter upgrade available in the Oasis Lounge.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$318", image: { src: "/images/services/couples-swedish-massage-hero.jpg", alt: "Share Relaxation, Side by Side at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50-minute couples Swedish massage in our private Bamboo Suite. Wine and cheese platter upgrade available in the Oasis Lounge.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$318" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Couples Relaxation", description: "Side-by-side massage creates a shared relaxation experience — perfect for anniversaries, date nights, or just because." }, { area: "Private Suite Experience", description: "The Bamboo Suite provides an intimate, serene setting exclusively for your session." }, { area: "Individual Tension", description: "Each person receives a full Swedish massage customized to their individual tension areas." }, { area: "Connection", description: "Shared experiences strengthen bonds. Walking out relaxed together is better than relaxing alone." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};