// src/content/services/cupping-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Cupping Massage Chicago | $109–$145 | Essence Medspa", description: "Ancient Technique, Modern Relief 50 or 80-minute treatment using silicone cupping for increased circulation, fascia release, and deep... At Essence Medspa Chicago. $109–$145.", keywords: ["cupping massage Chicago", "cupping massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/cupping-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Ancient Technique, Modern Relief", subheadline: "50 or 80-minute treatment using silicone cupping for increased circulation, fascia release, and deep tension relief. Particularly effective for back and shoulder tension.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$109–$145", image: { src: "/images/services/cupping-massage-hero.jpg", alt: "Ancient Technique, Modern Relief at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50 or 80-minute treatment using silicone cupping for increased circulation, fascia release, and deep tension relief. Particularly effective for back and shoulder tension.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$109–$145" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Fascia Restrictions", description: "Suction lifts and stretches fascia — the connective tissue layer that becomes tight and restricted." }, { area: "Upper Back Tension", description: "Cupping is exceptionally effective for the broad, flat muscles of the upper back." }, { area: "IT Band Tightness", description: "Runners and cyclists benefit from cupping along the iliotibial band." }, { area: "Circulation Issues", description: "Suction dramatically increases blood flow to treated areas, bringing nutrients and removing waste." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};