// src/content/services/custom-facial.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Custom Facial Chicago | Personalized Skin Treatment | $169 | Essence Medspa", description: "Custom facial at Essence Medspa Chicago. 50-minute fully personalized facial tailored to your unique skin concerns. $169. Every treatment is different because every skin is different.", keywords: ["custom facial Chicago", "personalized facial near me", "bespoke facial treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/custom-facial" },
  hero: { eyebrow: "Facial Treatments", headline: "Your Skin. Your Treatment. Your Results.", subheadline: "No two skins are the same — your facial shouldn't be either. Our Custom Facial starts with a thorough analysis and builds a treatment protocol unique to your concerns, your skin type, and your goals.", primaryCTA: { text: "Book Custom Facial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$169 · 50 minutes · Fully Personalized", image: { src: "/images/services/custom-facial-hero.jpg", alt: "Personalized custom facial at Essence Medspa Chicago" } },
  overview: { headline: "What Is a Custom Facial?", body: "The Custom Facial is our most flexible treatment — a 50-minute session that's built from scratch after your aesthetician analyzes your skin under magnification. Based on what they see, they select the cleanser, exfoliant, mask, serums, and techniques that will produce the best result for you that day.\n\nThis means your Custom Facial might focus on hydration one month and congestion the next. It adapts to seasonal changes, hormonal fluctuations, and evolving skin concerns. If you're not sure which facial to book, this is the answer.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Approach", value: "Fully customized after skin analysis" }, { label: "Downtime", value: "None" }, { label: "Price", value: "$169" }, { label: "Ideal For", value: "Any skin type or concern" }] },
  benefits: { headline: "What It Addresses", items: [{ area: "Multiple Concerns at Once", description: "Oily T-zone but dry cheeks? Sensitive areas with congested pores? Custom facials address contradictory concerns in a single session." }, { area: "Seasonal Skin Changes", description: "Your skin behaves differently in Chicago's dry winters versus humid summers. A custom approach adapts each time." }, { area: "First-Time Clients", description: "If you've never had a professional facial, a Custom Facial is the perfect starting point — your aesthetician learns your skin and recommends your ideal treatment path." }, { area: "Maintenance Between Treatments", description: "Between more intensive treatments like peels or micro-needling, a Custom Facial keeps skin healthy without interfering with your treatment plan." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Skin Analysis", description: "Your aesthetician examines your skin under magnification, asks about your routine and concerns, and designs the session." }, { step: "02", title: "Cleanse & Exfoliate", description: "Products selected specifically for your skin type — enzyme, physical, or chemical exfoliation based on what you need." }, { step: "03", title: "Treatment & Mask", description: "Targeted serums, extractions if needed, and a mask chosen for your primary concern. Massage techniques promote circulation." }, { step: "04", title: "Protect & Advise", description: "Finishing products lock in results. Your aesthetician recommends home care and when to return." }] },
  faqs: [
    { question: "What if I don't know what my skin needs?", answer: "That's exactly what this facial is for. Your aesthetician will assess your skin and make all the decisions. You just relax." },
    { question: "Will it include extractions?", answer: "Only if your skin needs them. Your aesthetician will incorporate extractions if they see congestion, but won't do unnecessary extractions on clear skin." },
    { question: "How is this different from the Hydrofacial?", answer: "The Hydrofacial uses a specific device and protocol. The Custom Facial is entirely manual and hand-selected by your aesthetician — more flexible but different in approach. Both are excellent; it depends on your preference." },
  ],
  relatedServices: { headline: "Explore Specialized Options", items: [{ name: "Hydrofacial", slug: "hydrofacial", tagline: "Device-driven deep cleansing and hydration" }, { name: "Brightening Facial", slug: "brightening-facial", tagline: "Specifically for dull, uneven skin" }, { name: "Acne Facial", slug: "acne-facial", tagline: "Specifically for breakout-prone skin" }] },
  finalCTA: { headline: "Let Your Skin Decide", subheadline: "Book a Custom Facial. Your aesthetician handles the rest.", primaryCTA: { text: "Book Custom Facial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};