// src/content/services/custom-peel.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Custom Chemical Peel Chicago | Starting at $130 | Essence Medspa", description: "Custom chemical peel at Essence Medspa Chicago. 30-minute results-driven peel customized for pigmentation, acne, fine lines, and mature skin. Starting at $130.", keywords: ["chemical peel Chicago", "custom peel near me", "skin peel Edgebrook", "facial peel Chicago"], canonical: "https://www.essence-medspa.com/services/custom-peel" },
  hero: { eyebrow: "Facial Treatments", headline: "Results-Driven Exfoliation, Customized for You", subheadline: "Our 30-minute Custom Peel is formulated on the spot by your aesthetician — acid type, concentration, and application time all tailored to your skin type, concerns, and tolerance.", primaryCTA: { text: "Book Custom Peel", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "Starting at $130 · 30 minutes", image: { src: "/images/services/custom-peel-hero.jpg", alt: "Custom chemical peel treatment at Essence Medspa Chicago" } },
  overview: { headline: "What Is a Custom Peel?", body: "A chemical peel uses controlled acid application to accelerate cell turnover — removing damaged surface cells and triggering the skin to produce fresh, healthy replacements. Our Custom Peel is not a one-size-fits-all treatment. Your aesthetician selects from glycolic, lactic, salicylic, mandelic, and TCA acids at varying concentrations based on your specific concerns.\n\nLighter peels produce a healthy glow with no peeling. Medium peels cause 2–3 days of flaking. Stronger peels may cause 4–5 days of visible peeling but deliver more dramatic results. Your aesthetician will match the intensity to your goals and schedule.", keyFacts: [{ label: "Treatment Time", value: "30 minutes" }, { label: "Downtime", value: "0–5 days depending on depth" }, { label: "Starting Price", value: "$130" }, { label: "Frequency", value: "Every 4–6 weeks" }, { label: "Skin Types", value: "Customized for all" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Hyperpigmentation", description: "Acid exfoliation lifts pigmented cells from the surface while stimulating fresh, evenly-toned replacement cells." }, { area: "Acne & Congestion", description: "Salicylic acid peels penetrate oily pores to dissolve congestion and prevent future breakouts." }, { area: "Fine Lines & Wrinkles", description: "Cell turnover and collagen stimulation smooth surface lines over a series of treatments." }, { area: "Sun Damage", description: "Progressive peels reverse years of UV damage by replacing damaged cells with healthy new ones." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Skin Assessment", description: "Your aesthetician evaluates your skin type, Fitzpatrick type, and concerns to select the optimal acid and concentration." }, { step: "02", title: "Prep & Application", description: "Skin is prepped and the custom peel solution is applied in controlled passes. Mild tingling or warmth is normal." }, { step: "03", title: "Neutralization", description: "The peel is neutralized at the precise time for your skin. Soothing serum calms the treated area." }, { step: "04", title: "Recovery & Results", description: "Aftercare products protect healing skin. Peeling (if any) occurs days 2–5. Fresh, renewed skin revealed beneath." }] },
  faqs: [
    { question: "Will my face actually peel?", answer: "Depends on the peel depth. Light peels produce glow without visible peeling. Medium to deep peels cause flaking on days 2–5. Your aesthetician will discuss this before treatment so there are no surprises." },
    { question: "How many peels do I need?", answer: "A single peel produces noticeable improvement. A series of 3–6 peels spaced 4–6 weeks apart produces the most dramatic cumulative results for pigmentation and scarring." },
    { question: "Can I get a peel in summer?", answer: "Yes, with strict sun protection afterward. Lighter peels are preferred in summer. Your aesthetician will adjust the formulation for the season." },
    { question: "Is a peel or microdermabrasion better for me?", answer: "Peels work chemically (dissolving dead cells); microdermabrasion works physically (removing them). Peels penetrate deeper and are better for pigmentation. Microdermabrasion is gentler with zero peeling. We can recommend the best option during consultation." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Microdermabrasion", slug: "microdermabrasion-facial", tagline: "Physical exfoliation complement" }, { name: "Meso Brightening", slug: "meso-brightening", tagline: "Deep brightening for stubborn pigmentation" }, { name: "Acne Facial", slug: "acne-facial", tagline: "Clear active acne before peeling" }] },
  finalCTA: { headline: "Ready for Renewed Skin?", subheadline: "Book a Custom Peel. Your aesthetician will tailor the formula to your skin.", primaryCTA: { text: "Book Custom Peel", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};