// src/content/services/deep-tissue-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Deep Tissue Massage Chicago | $130–$169 | Essence Medspa", description: "Reach the Knots Others Can't 50 or 80-minute deep pressure massage targeting chronic muscle tension, adhesions, and trigger point... At Essence Medspa Chicago. $130–$169.", keywords: ["deep tissue massage Chicago", "deep tissue massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/deep-tissue-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Reach the Knots Others Can't", subheadline: "50 or 80-minute deep pressure massage targeting chronic muscle tension, adhesions, and trigger points. Focused, intense work for serious relief.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$130–$169", image: { src: "/images/services/deep-tissue-massage-hero.jpg", alt: "Reach the Knots Others Can't at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50 or 80-minute deep pressure massage targeting chronic muscle tension, adhesions, and trigger points. Focused, intense work for serious relief.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$130–$169" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Chronic Knots & Adhesions", description: "Sustained deep pressure breaks down adhesions and releases trigger points that restrict movement." }, { area: "Lower Back Pain", description: "Targeted deep work on the lumbar region and surrounding muscles provides significant relief." }, { area: "Neck & Shoulder Tension", description: "Focused attention on the upper trapezius, levator scapulae, and neck muscles — the most common tension zones." }, { area: "Muscle Recovery", description: "Deep tissue work flushes metabolic waste and increases blood flow for faster muscle recovery." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};