// src/content/services/deep-pore-cleansing-facial.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Deep Pore Cleansing Facial Chicago | $125 | Essence Medspa", description: "Professional deep pore cleansing facial at Essence Medspa Chicago. 50-minute intensive pore detox with extractions for congested, oily skin. $125.", keywords: ["deep pore cleansing facial Chicago", "deep pore cleansing facial near me", "facial treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/deep-pore-cleansing-facial" },
  hero: { eyebrow: "Facial Treatments", headline: "The Ultimate Skin Detox", subheadline: "A 50-minute intensive pore detox with professional extractions. Clears congestion, removes impurities, and resets oily or breakout-prone skin to a clean slate.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$125 · 50 minutes", image: { src: "/images/services/deep-pore-cleansing-facial-hero.jpg", alt: "The Ultimate Skin Detox treatment at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "The Deep Pore Cleansing Facial is our most thorough detox treatment — 50 minutes dedicated to clearing everything that's clogging your skin. Beginning with steam to open pores, followed by enzyme softening, meticulous professional extraction, and a purifying clay mask.\n\nThis facial is ideal for anyone dealing with congestion, blackheads, excess oil, or a “gritty” skin texture. It's also an excellent seasonal reset — particularly after Chicago summers when heat and humidity drive excess oil production.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Downtime", value: "None to minimal" }, { label: "Price", value: "$125" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Clogged Pores", description: "Thorough professional extractions clear blackheads, whiteheads, and deep congestion." }, { area: "Oily Skin", description: "Deep cleansing removes excess sebum and regulates oil production." }, { area: "Breakout Prevention", description: "Removing congestion before it becomes inflamed acne saves your skin from future breakouts." }, { area: "Dull Texture", description: "Clearing the pore layer reveals smoother, more refined skin texture." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Skin Assessment", description: "Your aesthetician evaluates your skin and customizes the session." }, { step: "02", title: "Cleanse & Prep", description: "Thorough double cleanse prepares your skin for treatment." }, { step: "03", title: "Active Treatment", description: "The core treatment protocol is applied with professional-grade products." }, { step: "04", title: "Protect & Finish", description: "Hydrating finishing products and SPF protect your results." }] },
  faqs: [
    { question: "How often should I get this facial?", answer: "Every 4–6 weeks for maintained results. Your aesthetician will recommend the ideal frequency based on your skin's response." },
    { question: "Can I wear makeup after?", answer: "We recommend waiting a few hours for optimal absorption. Most clients find their skin looks so good they don't want to cover it up." },
    { question: "Is this treatment suitable for sensitive skin?", answer: "Your aesthetician will assess your skin's sensitivity level and adjust products and techniques accordingly. Many of our facials can be modified for sensitive skin." },
  ],
  relatedServices: { headline: "Explore More Facials", items: [{ name: "Custom Facial", slug: "custom-facial", tagline: "Fully personalized to your exact needs" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "Device-driven deep cleansing and glow" }, { name: "Brightening Facial", slug: "brightening-facial", tagline: "Vitamin C-powered radiance" }] },
  finalCTA: { headline: "Ready to Transform Your Skin?", subheadline: "Book your facial today. Expert care, visible results.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};