// src/content/services/face-lifting-gua-sha.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Face Lifting Gua Sha Chicago | $125 | Essence Medspa", description: "Sculpt, Drain, and Lift the Face 50-minute facial massage using ancient Gua Sha technique for lymphatic drainage, facial sculpting, a... At Essence Medspa Chicago. $125.", keywords: ["face lifting gua sha Chicago", "face lifting gua sha near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/face-lifting-gua-sha" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Sculpt, Drain, and Lift the Face", subheadline: "50-minute facial massage using ancient Gua Sha technique for lymphatic drainage, facial sculpting, and radiance. Stone tool meets skilled hands.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$125", image: { src: "/images/services/face-lifting-gua-sha-hero.jpg", alt: "Sculpt, Drain, and Lift the Face at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50-minute facial massage using ancient Gua Sha technique for lymphatic drainage, facial sculpting, and radiance. Stone tool meets skilled hands.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$125" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Facial Puffiness", description: "Gua Sha's sweeping motions move stagnant lymph fluid for immediate de-puffing." }, { area: "Jawline & Cheekbone Definition", description: "Targeted sculpting strokes enhance natural bone structure and facial contours." }, { area: "Dull Complexion", description: "Increased blood circulation brings fresh oxygen to the skin for instant radiance." }, { area: "Facial Tension", description: "Jaw clenching, brow furrowing, and other tension patterns are released through Gua Sha work." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};