// src/content/services/face-lymphatic-drainage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Face Lymphatic Drainage Chicago | $95 | Essence Medspa", description: "De-Puff and Detoxify 30-minute facial lymphatic drainage to reduce fluid retention, puffiness, and toxin buildup. Gentle ... At Essence Medspa Chicago. $95.", keywords: ["face lymphatic drainage Chicago", "face lymphatic drainage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/face-lymphatic-drainage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "De-Puff and Detoxify", subheadline: "30-minute facial lymphatic drainage to reduce fluid retention, puffiness, and toxin buildup. Gentle rhythmic technique for a more defined, youthful appearance.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$95", image: { src: "/images/services/face-lymphatic-drainage-hero.jpg", alt: "De-Puff and Detoxify at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "30-minute facial lymphatic drainage to reduce fluid retention, puffiness, and toxin buildup. Gentle rhythmic technique for a more defined, youthful appearance.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$95" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Facial Puffiness", description: "Rhythmic drainage techniques move excess fluid from the face for immediate de-puffing." }, { area: "Under-Eye Bags", description: "Lymphatic drainage reduces fluid that accumulates under the eyes, creating bags and shadows." }, { area: "Post-Procedure Swelling", description: "Gentle drainage accelerates recovery after injectables, facials, or other treatments." }, { area: "Sinus Congestion", description: "Drainage pathways in the face help relieve sinus pressure and congestion." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};