// src/content/services/foot-reflexology.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Foot Reflexology Chicago | $75–$95 | Essence Medspa", description: "Your Whole Body, Through Your Feet 30 or 45-minute focused foot treatment stimulating specific pressure points that correspond to organ... At Essence Medspa Chicago. $75–$95.", keywords: ["foot reflexology Chicago", "foot reflexology near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/foot-reflexology" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Your Whole Body, Through Your Feet", subheadline: "30 or 45-minute focused foot treatment stimulating specific pressure points that correspond to organs and systems throughout the body.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$75–$95", image: { src: "/images/services/foot-reflexology-hero.jpg", alt: "Your Whole Body, Through Your Feet at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "30 or 45-minute focused foot treatment stimulating specific pressure points that correspond to organs and systems throughout the body.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$75–$95" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Tension & Stress", description: "Specific foot pressure points trigger relaxation responses throughout the entire body." }, { area: "Energy Depletion", description: "Reflexology stimulates nerve endings that boost energy and reduce fatigue." }, { area: "Digestive Issues", description: "Pressure points on the feet corresponding to the digestive system can support healthy digestion." }, { area: "Foot Pain & Fatigue", description: "Direct attention to overworked feet provides immediate relief and comfort." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};