// src/content/services/glutathione-brightening.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Glutathione Skin Brightening Chicago | IV Push | $79 | Essence Medspa", description: "IV glutathione push at Essence Medspa Chicago. The body's master antioxidant for internal skin brightening and radiance. Just $79 per session. Book today.", keywords: ["glutathione IV Chicago", "skin brightening IV near me", "glutathione push Edgebrook", "internal skin brightening"], canonical: "https://www.essence-medspa.com/services/glutathione-brightening" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Glow from the Inside Out", subheadline: "Glutathione is your body's master antioxidant — and at $79 per IV push, it's the most accessible way to brighten your skin from within. Inhibits melanin production, detoxifies cells, and creates a lit-from-within radiance.", primaryCTA: { text: "Book Glutathione", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$79 · 15-minute session", image: { src: "/images/services/glutathione-hero.jpg", alt: "IV glutathione brightening push at Essence Medspa Chicago" } },
  overview: { headline: "What Is Glutathione IV?", body: "Glutathione is a tripeptide naturally produced by your body that functions as the master antioxidant — it protects cells from oxidative damage, supports detoxification, and plays a direct role in skin color regulation by inhibiting tyrosinase, the enzyme responsible for melanin production.\n\nOral glutathione supplements have poor absorption — your digestive system breaks down most of it before it reaches your bloodstream. IV delivery bypasses digestion entirely, delivering 100% of the glutathione directly to your cells. The result: more effective skin brightening, better detoxification, and systemic antioxidant protection in a quick 15-minute push.", keyFacts: [{ label: "Treatment Time", value: "15 minutes" }, { label: "Results", value: "Progressive (3–4 sessions)" }, { label: "Frequency", value: "Weekly initially, then monthly" }, { label: "Downtime", value: "None" }, { label: "Price", value: "$79" }] },
  benefits: { headline: "Benefits of Glutathione IV", items: [{ area: "Skin Brightening", description: "Inhibits melanin production for a brighter, more even skin tone over a series of sessions." }, { area: "Antioxidant Protection", description: "Neutralizes free radicals that accelerate aging, UV damage, and cellular breakdown." }, { area: "Detoxification", description: "Supports liver function and cellular detox, removing waste products that dull skin from within." }, { area: "Energy & Recovery", description: "Many clients report improved energy levels and faster recovery from illness or fatigue." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Quick Setup", description: "A small IV line is placed in your arm — similar to a blood draw." }, { step: "02", title: "Glutathione Push", description: "Concentrated glutathione is pushed through the IV over about 15 minutes. You can read, scroll, or relax." }, { step: "03", title: "Done", description: "The IV is removed, a small bandage is placed, and you're free to go. No restrictions, no downtime." }] },
  faqs: [
    { question: "How many sessions until I see brighter skin?", answer: "Most clients notice a difference after 3–4 weekly sessions. For significant brightening, we recommend 8–12 sessions in the initial phase, then monthly maintenance." },
    { question: "Is IV glutathione safe?", answer: "Glutathione is naturally produced by your body. IV supplementation has an excellent safety profile. Side effects are rare and typically limited to mild discomfort at the injection site." },
    { question: "Can I combine glutathione with other treatments?", answer: "Absolutely — it pairs beautifully with Meso Brightening for inside-out brightening, or with any facial treatment for enhanced results." },
    { question: "Will my skin go back to its original tone if I stop?", answer: "Gradually, yes — your body continues producing melanin naturally. Monthly maintenance sessions preserve the brightening effect." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Meso Brightening", slug: "meso-brightening", tagline: "External brightening to complement internal" }, { name: "Brightening Facial", slug: "brightening-facial", tagline: "Surface-level Vitamin C brightening" }, { name: "IV Therapy — Cosmetic", slug: "iv-therapy-cosmetic", tagline: "Full vitamin cocktail for skin and energy" }] },
  finalCTA: { headline: "Ready to Brighten from Within?", subheadline: "Book a glutathione IV push. 15 minutes, $79, zero downtime.", primaryCTA: { text: "Book Glutathione IV", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
