// src/content/services/hair-restoration.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "PRP Hair Restoration Chicago | Non-Surgical | Starting at $499 | Essence Medspa", description: "PRP hair restoration at Essence Medspa Chicago. Non-surgical treatment to reactivate dormant follicles and regrow thicker, stronger hair. Starting at $499. See results in 6–8 weeks.", keywords: ["PRP hair restoration Chicago", "hair loss treatment near me", "non-surgical hair regrowth Edgebrook", "hair thinning treatment Chicago"], canonical: "https://www.essence-medspa.com/services/hair-restoration" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Reactivate. Regrow. Reclaim Your Hair.", subheadline: "PRP hair restoration injects concentrated growth factors from your own blood directly into your scalp to wake dormant follicles, strengthen existing hair, and stimulate new growth — without drugs, surgery, or hormones.", primaryCTA: { text: "Book Consultation", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "Starting at $499 · Non-Surgical", image: { src: "/images/services/hair-restoration-hero.jpg", alt: "PRP hair restoration treatment showing new hair growth at Essence Medspa Chicago" }, stats: [{ value: "6–8", label: "Weeks to First New Growth" }, { value: "3", label: "Initial Sessions Recommended" }, { value: "30", suffix: " min", label: "Treatment Time" }] },
  overview: { headline: "What Is PRP Hair Restoration?", body: "PRP (platelet-rich plasma) hair restoration is a non-surgical treatment that uses your own blood's concentrated growth factors to stimulate hair regrowth. A small blood sample is drawn, processed in a centrifuge to isolate the platelet-rich plasma, and then injected directly into areas of thinning on your scalp.\n\nThe growth factors in PRP stimulate dormant hair follicles, extend the growth phase of the hair cycle, increase blood supply to the follicles, and strengthen existing hair shafts. Clinical studies show increased hair count and thickness in the majority of patients with androgenetic alopecia (pattern hair loss). The treatment works for both men and women.", keyFacts: [{ label: "Treatment Time", value: "30–45 minutes" }, { label: "First Results", value: "6–8 weeks" }, { label: "Full Results", value: "4–6 months" }, { label: "Initial Sessions", value: "3 (spaced 4–6 weeks apart)" }, { label: "Maintenance", value: "Every 3–6 months" }, { label: "Starting Price", value: "$499" }] },
  benefits: { headline: "What PRP Treats", items: [{ area: "Male Pattern Thinning", description: "Receding hairline, crown thinning, and general male pattern hair loss respond well when caught early to moderate stages." }, { area: "Female Hair Thinning", description: "Diffuse thinning across the crown and overall density loss in women — often triggered by hormones, stress, or aging." }, { area: "Postpartum Hair Loss", description: "Accelerates recovery from the temporary but distressing hair shedding that occurs after pregnancy." }, { area: "Stress-Related Shedding", description: "Telogen effluvium (stress-triggered hair loss) responds to PRP's growth factor stimulation." }] },
  process: { headline: "Your Hair Restoration Journey", steps: [{ step: "01", title: "Scalp Assessment", description: "We photograph your scalp, assess thinning patterns, and determine candidacy. Not every type of hair loss responds to PRP — honest assessment upfront." }, { step: "02", title: "Blood Draw & Processing", description: "A blood sample is drawn and processed in a centrifuge to concentrate the platelets and growth factors." }, { step: "03", title: "Numbing & Injection", description: "Topical numbing is applied to the scalp. PRP is injected into the thinning areas using a fine needle in a grid pattern." }, { step: "04", title: "Progressive Growth", description: "New growth typically appears at 6–8 weeks. Full density improvement visible at 4–6 months. Progress is documented with photos at each visit." }] },
  pricing: { headline: "Hair Restoration Pricing", tiers: [{ name: "Single PRP Session", price: "$499", description: "Individual PRP hair treatment session. Ideal for maintenance after completing the initial series.", includes: ["Scalp assessment", "Blood processing", "Full treatment"] }, { name: "Initial Series (3 Sessions)", price: "$1,350", description: "Three PRP sessions spaced 4–6 weeks apart. The recommended starting protocol for optimal follicle reactivation.", includes: ["$150 savings vs individual sessions", "Progress photography", "Maintenance plan"], popular: true }], disclaimer: "ASSUMPTION: Package pricing — verify with actual pricing structure. Individual results vary based on degree of thinning and follicle health." },
  faqs: [
    { question: "Who is a good candidate for PRP hair restoration?", answer: "People in the early to moderate stages of thinning where follicles are dormant but not completely gone. Both men and women benefit. Clients with very advanced hair loss (completely bald areas with no follicles remaining) may not see significant regrowth." },
    { question: "Does it work for receding hairlines?", answer: "PRP can thicken and strengthen hair in areas where follicles still exist but are producing thin, miniaturized hairs. It's most effective at the crown and midscalp. Completely bald temple points may have limited response." },
    { question: "Is it painful?", answer: "Topical numbing cream is applied before injections. Most clients describe mild discomfort — pressure and occasional pinching. The treatment is very tolerable, and the numbing makes a significant difference." },
    { question: "Can I combine PRP with other hair treatments?", answer: "Yes — we often combine PRP with Jet Plasma Scalp treatment to optimize the scalp environment. A healthy scalp allows follicles to respond better to the growth factors." },
    { question: "Are results permanent?", answer: "PRP reactivates follicles but doesn't permanently alter the underlying cause of hair loss (usually genetics or hormones). Maintenance sessions every 3–6 months are needed to sustain results. Think of it as ongoing care, similar to how you'd maintain any other aspect of your health." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Jet Plasma Scalp", slug: "jet-plasma-scalp", tagline: "Optimize scalp health for better PRP response" }, { name: "PRF Facial", slug: "prf-facial", tagline: "PRF can also be applied to the scalp for slow-release growth factors" }, { name: "IV Therapy — Recovery", slug: "iv-therapy-recovery", tagline: "Support overall health during the restoration process" }] },
  finalCTA: { headline: "Ready to Start Your Hair Restoration Journey?", subheadline: "Book a scalp assessment. We'll photograph your thinning areas, evaluate your candidacy, and create an honest treatment plan.", primaryCTA: { text: "Book Hair Restoration", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
