// src/content/services/hot-stone-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Hot Stone Massage Chicago | $160–$195 | Essence Medspa", description: "Heated Stones, Deeper Healing 50 or 80-minute massage using heated basalt stones placed on tension points. Deep warmth relaxes mus... At Essence Medspa Chicago. $160–$195.", keywords: ["hot stone massage Chicago", "hot stone massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/hot-stone-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Heated Stones, Deeper Healing", subheadline: "50 or 80-minute massage using heated basalt stones placed on tension points. Deep warmth relaxes muscles faster, allowing the therapist to work more effectively.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$160–$195", image: { src: "/images/services/hot-stone-massage-hero.jpg", alt: "Heated Stones, Deeper Healing at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50 or 80-minute massage using heated basalt stones placed on tension points. Deep warmth relaxes muscles faster, allowing the therapist to work more effectively.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$160–$195" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Deep Muscle Stiffness", description: "Heated stones penetrate warmth deep into muscle tissue, relaxing fibers more effectively than hands alone." }, { area: "Chronic Pain", description: "Sustained heat application reduces pain perception and increases range of motion." }, { area: "Stress & Anxiety", description: "The warmth and weight of hot stones creates a deeply grounding, meditative experience." }, { area: "Poor Circulation", description: "Heat dilates blood vessels, improving circulation to stiff, painful areas." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};