// src/content/services/hyaluronidase-dissolve.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Hyaluronidase Filler Dissolving Chicago | $175 | Essence Medspa", description: "Dissolve unwanted or migrated filler at Essence Medspa Chicago. Hyaluronidase enzyme treatment to reset and restore your natural look. $175. Safe, controlled correction.", keywords: ["filler dissolving Chicago", "hyaluronidase near me", "dissolve lip filler Edgebrook", "filler correction Chicago"], canonical: "https://www.essence-medspa.com/services/hyaluronidase-dissolve" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Reset and Restore Your Natural Look", subheadline: "Whether you're unhappy with previous filler results, experiencing migration, or simply want a fresh start — hyaluronidase safely dissolves hyaluronic acid filler so you can begin again.", primaryCTA: { text: "Book Dissolving Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$175 · Safe Filler Correction", image: { src: "/images/services/hyaluronidase-hero.jpg", alt: "Filler dissolving treatment for natural restoration at Essence Medspa" } },
  overview: { headline: "What Is Hyaluronidase?", body: "Hyaluronidase is a naturally occurring enzyme that breaks down hyaluronic acid — the same substance used in Juvederm, Restylane, and most popular dermal fillers. When injected into an area with unwanted filler, it dissolves the HA molecules, allowing your body to absorb and eliminate them naturally.\n\nThis treatment is the safety net of the filler world. Whether filler has migrated, been placed asymmetrically, caused lumps, or simply isn't what you wanted — hyaluronidase provides a controlled, predictable way to undo it. Results are visible within 24–48 hours, and once fully dissolved, you can choose to have new filler placed or enjoy your natural features.", keyFacts: [{ label: "Treatment Time", value: "15–30 minutes" }, { label: "Results", value: "24–48 hours" }, { label: "Downtime", value: "Minimal swelling 1–2 days" }, { label: "Price", value: "$175" }, { label: "Dissolves", value: "All HA-based fillers" }] },
  benefits: { headline: "When Dissolving Is the Right Choice", items: [{ area: "Filler Migration", description: "Filler that has moved from its intended location — common in lips and under eyes. Hyaluronidase removes it from where it shouldn't be." }, { area: "Overfilled Results", description: "Too much volume creating an unnatural appearance. Dissolving allows a controlled reset." }, { area: "Asymmetry", description: "Uneven filler placement can be corrected by dissolving one side and starting fresh." }, { area: "Lumps or Nodules", description: "Palpable lumps under the skin from filler that didn't settle properly." }, { area: "Fresh Start", description: "Some clients accumulate filler over years and want to reset to their natural baseline before re-approaching their aesthetic plan." }] },
  process: { headline: "Your Dissolving Experience", steps: [{ step: "01", title: "Assessment", description: "We evaluate the filler location, determine the amount of hyaluronidase needed, and discuss your goals — full dissolution or partial correction." }, { step: "02", title: "Allergy Test (if needed)", description: "For first-time hyaluronidase clients, a small test dose may be placed to check for rare allergic sensitivity." }, { step: "03", title: "Injection", description: "Hyaluronidase is injected directly into the area with unwanted filler. The enzyme begins working immediately." }, { step: "04", title: "Results & Next Steps", description: "Dissolution is visible within 24–48 hours. A follow-up at 2 weeks confirms full results. If desired, new filler can be placed 2–4 weeks after dissolving." }] },
  faqs: [
    { question: "Does hyaluronidase dissolve all types of fillers?", answer: "It only dissolves hyaluronic acid (HA) based fillers like Juvederm, Restylane, and Belotero. It does not dissolve non-HA fillers like Radiesse, Sculptra, or silicone." },
    { question: "Will it dissolve my natural hyaluronic acid too?", answer: "The enzyme does temporarily affect natural HA in the area, but your body rapidly replenishes its own HA within 24–48 hours. There's no long-term depletion." },
    { question: "Can I get new filler after dissolving?", answer: "Yes — we recommend waiting 2–4 weeks after dissolving before placing new filler. This ensures the area has fully settled and the hyaluronidase is no longer active." },
    { question: "Is it painful?", answer: "There may be brief stinging during injection and mild swelling afterward. Most clients tolerate it well. The swelling resolves within 1–2 days." },
  ],
  relatedServices: { headline: "After Dissolving, Consider", items: [{ name: "Juvederm Fillers", slug: "juvederm-fillers", tagline: "Fresh filler with a new, improved placement plan" }, { name: "Botox", slug: "botox", tagline: "Address wrinkles alongside your reset" }, { name: "PRP Facial", slug: "prp-facial", tagline: "Natural skin rejuvenation instead of re-filling" }] },
  finalCTA: { headline: "Ready for a Fresh Start?", subheadline: "Book a dissolving consultation. We'll assess your current filler, discuss your goals, and create a correction plan.", primaryCTA: { text: "Book Dissolving Consultation", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
