// src/content/services/hydrofacial.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Hydrofacial Chicago | Oxygen & Water Facial | $229 | Essence Medspa", description: "Hydrofacial at Essence Medspa Chicago. 60-minute oxygen and water facial for instant glow, deep cleansing, and hydration. $229. Zero downtime. Book today.", keywords: ["Hydrofacial Chicago", "hydrafacial near me", "oxygen facial Edgebrook", "best facial Chicago"], canonical: "https://www.essence-medspa.com/services/hydrofacial" },
  hero: { eyebrow: "Facial Treatments", headline: "Chicago's Most Requested Glow Treatment", subheadline: "The Hydrofacial cleanses, extracts, and hydrates simultaneously using vortex suction and intensive serums. Walk in dull. Walk out glowing. Zero downtime.", primaryCTA: { text: "Book Hydrofacial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$229 · 60 minutes · Instant Results", image: { src: "/images/services/hydrofacial-hero.jpg", alt: "Hydrofacial treatment showing glowing results at Essence Medspa Chicago" }, stats: [{ value: "60", suffix: " min", label: "Treatment Time" }, { value: "0", label: "Days Downtime" }, { value: "3", label: "Steps in 1 Treatment" }] },
  overview: { headline: "What Is a Hydrofacial?", body: "The Hydrofacial is a multi-step facial that uses a patented vortex technology to cleanse, exfoliate, extract, and hydrate skin simultaneously. Unlike traditional facials that rely on manual techniques, the Hydrofacial device delivers consistent, deep results by combining gentle suction with a continuous flow of serums.\n\nStep 1 cleanses and exfoliates dead skin cells. Step 2 uses painless vortex suction to extract debris from pores without manual squeezing. Step 3 saturates the skin with intensive serums containing hyaluronic acid, peptides, and antioxidants. The result: immediately visible hydration, clarity, and glow — with zero redness and zero downtime.", keyFacts: [{ label: "Treatment Time", value: "60 minutes" }, { label: "Results", value: "Immediate" }, { label: "Downtime", value: "None" }, { label: "Skin Types", value: "All (including sensitive)" }, { label: "Price", value: "$229" }, { label: "Frequency", value: "Every 4–6 weeks" }] },
  benefits: { headline: "What the Hydrofacial Treats", items: [{ area: "Dull, Dehydrated Skin", description: "Three-step process floods skin with hydration and nutrients for immediate radiance." }, { area: "Clogged Pores & Congestion", description: "Vortex extraction clears pores deeply without painful manual squeezing." }, { area: "Fine Lines", description: "Hyaluronic acid and peptide serums plump skin, reducing the appearance of surface lines." }, { area: "Hyperpigmentation", description: "Exfoliation and brightening serums improve uneven skin tone and light discoloration." }, { area: "Oily Skin", description: "Deep cleansing removes excess oil while balancing hydration levels." }] },
  process: { headline: "Your Hydrofacial Experience", steps: [{ step: "01", title: "Cleanse + Exfoliate", description: "A gentle peel lifts away dead skin cells and surface debris, revealing fresh skin beneath." }, { step: "02", title: "Extract + Purify", description: "Painless vortex suction clears clogged pores while a nourishing solution dissolves impurities." }, { step: "03", title: "Hydrate + Infuse", description: "The skin is saturated with intensive serums customized for your skin concerns — antioxidants, hyaluronic acid, peptides." }, { step: "04", title: "Glow", description: "A protective moisturizer and SPF seal everything in. You're immediately ready for the rest of your day — or evening." }] },
  faqs: [
    { question: "Can I wear makeup immediately after?", answer: "Yes — there's zero downtime. Your skin will look so good you may not want to, but you're free to apply makeup right away." },
    { question: "How is a Hydrofacial different from a regular facial?", answer: "Traditional facials rely on manual techniques and steam. The Hydrofacial uses a patented device for more consistent, deeper results — especially in extraction and serum delivery. The results are more immediate and dramatic." },
    { question: "Is the extraction painful?", answer: "Not at all. Vortex suction extraction is painless — a significant upgrade over manual extraction. Most clients find it satisfying to see the debris that's removed." },
    { question: "How often should I get a Hydrofacial?", answer: "Every 4–6 weeks for maintained results. Monthly is ideal for most clients. Before a special event, book 2–3 days ahead for peak glow." },
    { question: "Is it good for sensitive skin?", answer: "Yes — the Hydrofacial is one of the gentlest yet most effective treatments we offer. The serums can be customized to avoid any ingredients that trigger sensitivity." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Glutathione Brightening", slug: "glutathione-brightening", tagline: "Internal glow to match external radiance" }, { name: "Meso Glow", slug: "meso-glow", tagline: "Deeper nourishment for lasting results" }, { name: "LED Light Therapy", slug: "custom-facial", tagline: "Add LED to boost hydrofacial results" }] },
  finalCTA: { headline: "Ready for Your Glow?", subheadline: "Book a Hydrofacial. 60 minutes, zero downtime, instant results.", primaryCTA: { text: "Book Hydrofacial", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
