// src/content/services/hydrating-facial.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Hydrating Facial Chicago | $159 | Essence Medspa", description: "Hydrating facial at Essence Medspa Chicago. 50-minute soothing treatment with thermo-cooling for sensitive and dehydrated skin. $159.", keywords: ["hydrating facial Chicago", "hydrating facial near me", "facial treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/hydrating-facial" },
  hero: { eyebrow: "Facial Treatments", headline: "Deep Relief for Parched Skin", subheadline: "A 50-minute soothing hydration treatment with thermo-cooling technology. Designed for sensitive and dehydrated skin that needs gentle, deep moisture restoration.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$159 · 50 minutes", image: { src: "/images/services/hydrating-facial-hero.jpg", alt: "Deep Relief for Parched Skin treatment at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "The Hydrating Facial is a 50-minute treatment built for skin that's dehydrated, sensitive, or both. Using thermo-cooling technology that keeps the skin calm while delivering hydrating actives, it restores moisture without triggering sensitivity.\n\nThe treatment layers hyaluronic acid, ceramides, and soothing botanicals to repair the moisture barrier, reduce transepidermal water loss, and plump dehydrated skin from within. It's particularly popular during Chicago's brutal winter months when heating systems and cold wind combine to strip skin of its natural moisture.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Downtime", value: "None to minimal" }, { label: "Price", value: "$159" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Chronic Dehydration", description: "Multi-layer hydration restores moisture at every skin level — surface and deep." }, { area: "Sensitive Skin", description: "Thermo-cooling technology soothes reactive skin while delivering active ingredients without irritation." }, { area: "Winter Skin Damage", description: "Chicago's dry winters strip skin of moisture. This facial replenishes what indoor heating and cold wind take away." }, { area: "Redness & Irritation", description: "Calming ingredients reduce redness and strengthen the skin's protective barrier." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Skin Assessment", description: "Your aesthetician evaluates your skin and customizes the session." }, { step: "02", title: "Cleanse & Prep", description: "Thorough double cleanse prepares your skin for treatment." }, { step: "03", title: "Active Treatment", description: "The core treatment protocol is applied with professional-grade products." }, { step: "04", title: "Protect & Finish", description: "Hydrating finishing products and SPF protect your results." }] },
  faqs: [
    { question: "How often should I get this facial?", answer: "Every 4–6 weeks for maintained results. Your aesthetician will recommend the ideal frequency based on your skin's response." },
    { question: "Can I wear makeup after?", answer: "We recommend waiting a few hours for optimal absorption. Most clients find their skin looks so good they don't want to cover it up." },
    { question: "Is this treatment suitable for sensitive skin?", answer: "Your aesthetician will assess your skin's sensitivity level and adjust products and techniques accordingly. Many of our facials can be modified for sensitive skin." },
  ],
  relatedServices: { headline: "Explore More Facials", items: [{ name: "Custom Facial", slug: "custom-facial", tagline: "Fully personalized to your exact needs" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "Device-driven deep cleansing and glow" }, { name: "Brightening Facial", slug: "brightening-facial", tagline: "Vitamin C-powered radiance" }] },
  finalCTA: { headline: "Ready to Transform Your Skin?", subheadline: "Book your facial today. Expert care, visible results.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};