// src/content/services/iv-therapy-cosmetic.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "IV Therapy Cosmetic Chicago | Vitamins for Skin & Energy | $230 | Essence Medspa", description: "Cosmetic IV therapy at Essence Medspa Chicago. Vitamins, minerals, and antioxidants delivered directly to your bloodstream for radiant skin and natural energy. $230.", keywords: ["IV therapy Chicago", "cosmetic IV drip near me", "vitamin IV skin Edgebrook", "beauty IV therapy Chicago"], canonical: "https://www.essence-medspa.com/services/iv-therapy-cosmetic" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Beauty from the Inside Out", subheadline: "Skip the supplements. Our Cosmetic IV delivers a potent cocktail of vitamins, minerals, and antioxidants directly to your cells — 100% absorption for glowing skin, natural energy, and whole-body vitality.", primaryCTA: { text: "Book Cosmetic IV", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$230 · 45-minute session", image: { src: "/images/services/iv-cosmetic-hero.jpg", alt: "Cosmetic IV therapy drip at Essence Medspa Chicago" } },
  overview: { headline: "What Is Cosmetic IV Therapy?", body: "Cosmetic IV therapy delivers a custom blend of vitamins (C, B-complex, biotin), minerals (zinc, selenium), amino acids, and antioxidants directly into your bloodstream through an IV drip. Unlike oral supplements that lose 20–50% of their potency through digestion, IV delivery achieves 100% bioavailability.\n\nOur Cosmetic IV formula is specifically designed to support skin health, collagen production, cellular repair, and natural energy. The vitamins and antioxidants work systemically — nourishing your skin, hair, nails, and immune system from within. Many clients describe feeling a noticeable boost in energy and clarity within hours.", keyFacts: [{ label: "Treatment Time", value: "45 minutes" }, { label: "Absorption", value: "100% bioavailability" }, { label: "Results", value: "Immediate energy; skin improvement over days" }, { label: "Downtime", value: "None" }, { label: "Price", value: "$230" }] },
  benefits: { headline: "What Cosmetic IV Treats", items: [{ area: "Skin Radiance", description: "High-dose Vitamin C and antioxidants protect skin cells and boost collagen production for visible radiance." }, { area: "Energy & Vitality", description: "B-complex vitamins and minerals restore natural energy without caffeine or stimulants." }, { area: "Hair & Nail Strength", description: "Biotin, zinc, and amino acids support stronger hair growth and nail health from within." }, { area: "Immune Support", description: "Zinc, Vitamin C, and selenium strengthen immune function while benefiting skin." }, { area: "Anti-Aging", description: "Antioxidants neutralize free radicals — the molecules responsible for cellular aging and skin damage." }] },
  process: { headline: "Your IV Experience", steps: [{ step: "01", title: "Brief Intake", description: "A quick health screening ensures the IV formula is appropriate for you." }, { step: "02", title: "IV Placement", description: "A small IV line is placed in your arm. Brief pinch, then comfortable." }, { step: "03", title: "Relax & Absorb", description: "The drip infuses over about 45 minutes. Read, work on your phone, or simply close your eyes." }, { step: "04", title: "Post-Drip Glow", description: "The IV is removed and you're free to go. Most clients feel the energy boost within hours. Skin benefits build over the following days." }] },
  faqs: [
    { question: "How often should I get a Cosmetic IV?", answer: "For optimal skin benefits, we recommend biweekly sessions during an initial boost phase (4–6 weeks), then monthly maintenance. For pre-event prep, a single session 2–3 days before is ideal." },
    { question: "Can I combine IV therapy with a facial?", answer: "Absolutely — treating skin from both inside and outside simultaneously produces the best results. Many clients pair a Cosmetic IV with a Hydrofacial or Brightening Facial." },
    { question: "Is IV therapy safe?", answer: "Yes — when administered by trained professionals using medical-grade ingredients. Side effects are rare and typically limited to mild discomfort at the IV site. We use sterile, single-use equipment for every treatment." },
    { question: "What's the difference between Cosmetic, Hydration, and Recovery IVs?", answer: "Cosmetic focuses on skin health, beauty nutrients, and energy. Hydration is pure rehydration for dehydration. Recovery is formulated for post-exercise, post-travel, or illness recovery. Each has a different formula optimized for its purpose." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Glutathione Brightening", slug: "glutathione-brightening", tagline: "Add a glutathione push for enhanced brightening" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "External glow to match your internal boost" }, { name: "Meso Glow", slug: "meso-glow", tagline: "Nourish skin from both directions simultaneously" }] },
  finalCTA: { headline: "Ready to Nourish from Within?", subheadline: "Book your Cosmetic IV. 45 minutes, zero downtime, visible results.", primaryCTA: { text: "Book Cosmetic IV", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
