// src/content/services/iv-therapy-recovery.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "IV Recovery Therapy Chicago | Post-Workout & Travel | $225 | Essence Medspa", description: "Recovery IV therapy at Essence Medspa Chicago. Post-workout, post-travel, and general rejuvenation infusion with vitamins and minerals. $225. Bounce back faster.", keywords: ["IV recovery Chicago", "recovery drip near me", "post-workout IV Edgebrook", "rejuvenation IV therapy"], canonical: "https://www.essence-medspa.com/services/iv-therapy-recovery" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Bounce Back Faster", subheadline: "Our Recovery IV replenishes everything your body burns through during intense workouts, travel, illness, or life. Hydration, vitamins, minerals, and anti-inflammatory compounds — delivered directly where your cells need them.", primaryCTA: { text: "Book Recovery IV", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$225 · 45-minute session", image: { src: "/images/services/iv-recovery-hero.jpg", alt: "Recovery IV therapy session at Essence Medspa Chicago" } },
  overview: { headline: "What Is Recovery IV Therapy?", body: "The Recovery IV is our most comprehensive infusion — designed to replenish, repair, and restore when your body has been pushed hard. The formula combines hydration with B-complex vitamins, magnesium, zinc, amino acids, and anti-inflammatory compounds to address multiple recovery pathways simultaneously.\n\nWhether you've just run a marathon, flown across the country, battled a cold, or simply burned the candle at both ends for too long — this IV gives your body the raw materials it needs to recover faster and more completely than rest alone.", keyFacts: [{ label: "Treatment Time", value: "45 minutes" }, { label: "Absorption", value: "100% bioavailability" }, { label: "Best For", value: "Post-exercise, travel, illness, fatigue" }, { label: "Downtime", value: "None" }, { label: "Price", value: "$225" }] },
  benefits: { headline: "What Recovery IV Supports", items: [{ area: "Muscle Recovery", description: "Amino acids and magnesium reduce soreness, support protein synthesis, and accelerate muscle repair after intense exercise." }, { area: "Travel Recovery", description: "Replenishes fluids, electrolytes, and nutrients depleted by flying, jet lag, and schedule disruption." }, { area: "Immune Rebound", description: "Zinc and Vitamin C support immune function during and after illness for faster recovery." }, { area: "General Rejuvenation", description: "B-vitamins and minerals restore energy, mental clarity, and overall vitality when burnout has set in." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Quick Assessment", description: "Brief health screening to confirm the Recovery formula is right for your situation." }, { step: "02", title: "IV Placement & Drip", description: "IV placed, drip started. The full infusion takes about 45 minutes." }, { step: "03", title: "Relax", description: "Sit back, close your eyes, or scroll your phone while the nutrients absorb." }, { step: "04", title: "Restored", description: "Most clients feel noticeably better within hours. Full recovery benefits continue for 24–48 hours." }] },
  faqs: [
    { question: "When should I get a Recovery IV relative to my workout?", answer: "Within 2–4 hours post-exercise is ideal for maximum recovery benefit. Some athletes also use it 24 hours before major events to pre-load nutrients." },
    { question: "How is Recovery IV different from Hydration IV?", answer: "Hydration IV is primarily fluids and electrolytes — great for pure dehydration. Recovery IV adds B-vitamins, magnesium, zinc, amino acids, and anti-inflammatory compounds for comprehensive physical recovery." },
    { question: "Can I add glutathione?", answer: "Yes — a glutathione push can be added to any IV for an additional brightening and antioxidant benefit. Ask your provider." },
  ],
  relatedServices: { headline: "Consider Also", items: [{ name: "IV Therapy — Hydration", slug: "iv-therapy-hydration", tagline: "Pure rehydration when that's all you need" }, { name: "IV Therapy — Cosmetic", slug: "iv-therapy-cosmetic", tagline: "Beauty-focused formula for skin and hair" }, { name: "Deep Tissue Massage", slug: "deep-tissue-massage", tagline: "Combine IV recovery with muscle work" }] },
  finalCTA: { headline: "Need to Bounce Back?", subheadline: "Book a Recovery IV. 45 minutes to feel restored.", primaryCTA: { text: "Book Recovery IV", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
