// src/content/services/iv-therapy-hydration.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "IV Hydration Therapy Chicago | Rapid Rehydration | $175 | Essence Medspa", description: "IV hydration therapy at Essence Medspa Chicago. Rapid rehydration delivered directly to your bloodstream. $175. Ideal for dehydration, fatigue, dry skin, and hangover recovery.", keywords: ["IV hydration Chicago", "hydration drip near me", "dehydration treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/iv-therapy-hydration" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Deep Cellular Rehydration in 30 Minutes", subheadline: "Drinking water hydrates gradually. IV hydration delivers fluids, electrolytes, and minerals directly to your cells for immediate, complete rehydration — when your body needs it most.", primaryCTA: { text: "Book Hydration IV", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$175 · 30-minute session", image: { src: "/images/services/iv-hydration-hero.jpg", alt: "IV hydration therapy session at Essence Medspa Chicago" } },
  overview: { headline: "What Is IV Hydration Therapy?", body: "IV hydration delivers a sterile saline solution enriched with electrolytes directly into your bloodstream. When you're dehydrated, drinking water takes hours to fully absorb through your digestive system. IV hydration bypasses digestion, delivering fluids to your cells immediately.\n\nThis treatment is ideal after travel, intense workouts, illness, hangovers, or simply when Chicago's dry winter air has left you feeling depleted. Many clients also book hydration IVs before events to ensure their skin looks plump and healthy.", keyFacts: [{ label: "Treatment Time", value: "30 minutes" }, { label: "Absorption", value: "100% — immediate" }, { label: "Results", value: "Feel it within minutes" }, { label: "Downtime", value: "None" }, { label: "Price", value: "$175" }] },
  benefits: { headline: "Who Benefits from IV Hydration", items: [{ area: "Post-Travel Dehydration", description: "Airplane cabins have 10–20% humidity. IV hydration restores what flying strips away." }, { area: "Hangover Recovery", description: "Alcohol is a diuretic. IV fluids rehydrate and replenish electrolytes for fast recovery." }, { area: "Athletic Performance", description: "Pre and post-workout hydration improves performance and accelerates recovery." }, { area: "Dry Skin & Fatigue", description: "Chronic mild dehydration causes dull skin and low energy. A single IV can reset both." }, { area: "Illness Recovery", description: "Fever, vomiting, and diarrhea deplete fluids rapidly. IV hydration restores them faster than oral intake." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Quick Intake", description: "Brief health screening and hydration assessment." }, { step: "02", title: "IV Placement", description: "Small IV line placed in your arm. Brief pinch, then comfortable." }, { step: "03", title: "Hydrate & Relax", description: "The hydration drip infuses over about 30 minutes. Most clients feel better before the bag is even empty." }, { step: "04", title: "Walk Out Refreshed", description: "IV removed, small bandage applied, and you're done. Most clients report feeling noticeably better immediately." }] },
  faqs: [
    { question: "Can't I just drink more water?", answer: "Oral hydration takes 1–2 hours to absorb and your body only retains a portion. IV hydration provides immediate, complete absorption. When you're significantly dehydrated, IV is dramatically more effective." },
    { question: "How often can I get an IV hydration drip?", answer: "As needed. Some clients come weekly during dry Chicago winters, others come before or after specific events. There's no strict frequency requirement." },
    { question: "Can I upgrade to a different formula?", answer: "Yes — if you want vitamins and minerals added, we can upgrade to our Cosmetic IV ($230) or Recovery IV ($225). The hydration base is the same; the additions target different benefits." },
  ],
  relatedServices: { headline: "Consider Also", items: [{ name: "IV Therapy — Cosmetic", slug: "iv-therapy-cosmetic", tagline: "Add skin-boosting vitamins to your hydration" }, { name: "IV Therapy — Recovery", slug: "iv-therapy-recovery", tagline: "Full recovery formula for post-workout or illness" }, { name: "Glutathione Brightening", slug: "glutathione-brightening", tagline: "Add a brightening push to any IV session" }] },
  finalCTA: { headline: "Feeling Dehydrated?", subheadline: "Book a Hydration IV. 30 minutes to feel like yourself again.", primaryCTA: { text: "Book Hydration IV", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
