// src/content/services/jet-plasma-hand.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Jet Plasma Hand Chicago | $250 | Essence Medspa", description: "Jet Plasma hand rejuvenation at Essence Medspa Chicago. 20-minute treatment for aging hands. $250.", keywords: ["jet plasma hand Chicago", "jet plasma hand near me"], canonical: "https://www.essence-medspa.com/services/jet-plasma-hand" },
  hero: { eyebrow: "Body Treatments", headline: "Rejuvenate Aging Hands", subheadline: "20-minute hand rejuvenation for sun damage, sun spots, aging, and wrinkles. Your hands often show age first — this treatment turns back the clock.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$250 · 20 minutes", image: { src: "/images/services/jet-plasma-hand-hero.jpg", alt: "Rejuvenate Aging Hands at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "20-minute hand rejuvenation for sun damage, sun spots, aging, and wrinkles. Your hands often show age first — this treatment turns back the clock.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "20 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$250" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Hand Sun Damage", description: "Plasma treatment targets accumulated sun damage and age spots on the hands." }, { area: "Hand Wrinkles", description: "Collagen stimulation firms and smooths thinning, wrinkled hand skin." }, { area: "Volume Loss", description: "Improved skin quality restores a more youthful hand appearance." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};