// src/content/services/jet-plasma-breast.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Jet Plasma Breast Chicago | $400 | Essence Medspa", description: "Jet Plasma breast treatment at Essence Medspa Chicago. 40-minute firming treatment. $400.", keywords: ["jet plasma breast Chicago", "jet plasma breast near me"], canonical: "https://www.essence-medspa.com/services/jet-plasma-breast" },
  hero: { eyebrow: "Body Treatments", headline: "Firm and Tighten the Breast Area", subheadline: "40-minute breast area treatment for fine lines, sagging, and firming. Restore firmer, smoother décolleté and breast area skin.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$400 · 40 minutes", image: { src: "/images/services/jet-plasma-breast-hero.jpg", alt: "Firm and Tighten the Breast Area at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "40-minute breast area treatment for fine lines, sagging, and firming. Restore firmer, smoother décolleté and breast area skin.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "40 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$400" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Breast Area Sagging", description: "Plasma energy firms and tightens skin on and around the breast area." }, { area: "Fine Lines", description: "Collagen stimulation smooths wrinkles and crepey texture." }, { area: "Loss of Firmness", description: "Improved skin elasticity creates a visibly firmer appearance." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};