// src/content/services/jet-plasma-face-neck.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Jet Plasma Face Neck Chicago | $450 | Essence Medspa", description: "Jet Plasma face and neck treatment at Essence Medspa Chicago. Combined rejuvenation for face and neck. $450.", keywords: ["jet plasma face neck Chicago", "jet plasma face neck near me"], canonical: "https://www.essence-medspa.com/services/jet-plasma-face-neck" },
  hero: { eyebrow: "Body Treatments", headline: "Comprehensive Face and Neck Rejuvenation", subheadline: "50-minute combined plasma treatment for fine lines, sagging, and dullness across both the face and neck in one session.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$450 · 50 minutes", image: { src: "/images/services/jet-plasma-face-neck-hero.jpg", alt: "Comprehensive Face and Neck Rejuvenation at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "50-minute combined plasma treatment for fine lines, sagging, and dullness across both the face and neck in one session.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$450" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Face + Neck Aging", description: "Treats both areas in one session for seamless rejuvenation — no visible line where treatment stops." }, { area: "Neck Sagging", description: "Plasma energy firms and tightens the neck area alongside the face." }, { area: "Fine Lines", description: "Both facial and neck lines are addressed with targeted plasma application." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};