// src/content/services/jet-plasma-decollete.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Jet Plasma Decollete Chicago | $109 | Essence Medspa", description: "Jet Plasma décolleté at Essence Medspa Chicago. 30-minute chest area treatment for sun damage and wrinkles. $109.", keywords: ["jet plasma decollete Chicago", "jet plasma decollete near me"], canonical: "https://www.essence-medspa.com/services/jet-plasma-decollete" },
  hero: { eyebrow: "Body Treatments", headline: "Renew the Chest Area", subheadline: "30-minute décolleté plasma treatment for sun damage, sun spots, aging, and wrinkles on the chest area.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$109 · 30 minutes", image: { src: "/images/services/jet-plasma-decollete-hero.jpg", alt: "Renew the Chest Area at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "30-minute décolleté plasma treatment for sun damage, sun spots, aging, and wrinkles on the chest area.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "30 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$109" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Chest Sun Damage", description: "Plasma application targets accumulated UV damage on the décolleté." }, { area: "Chest Wrinkles", description: "Fine lines and crepey chest skin are addressed with collagen-stimulating energy." }, { area: "Sun Spots", description: "Accelerates cell turnover to fade pigmented spots on the chest." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};