// src/content/services/jet-plasma-legs-knee.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Jet Plasma Legs Knee Chicago | $500 | Essence Medspa", description: "Jet Plasma legs and knee treatment at Essence Medspa Chicago. 50-minute treatment for crepey legs and knees. $500.", keywords: ["jet plasma legs knee Chicago", "jet plasma legs knee near me"], canonical: "https://www.essence-medspa.com/services/jet-plasma-legs-knee" },
  hero: { eyebrow: "Body Treatments", headline: "Restore Elasticity and Smooth Skin", subheadline: "50-minute legs and knees treatment for crepey skin and elasticity loss from aging or significant weight loss.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$500 · 50 minutes", image: { src: "/images/services/jet-plasma-legs-knee-hero.jpg", alt: "Restore Elasticity and Smooth Skin at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "50-minute legs and knees treatment for crepey skin and elasticity loss from aging or significant weight loss.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "50 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$500" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Crepey Leg Skin", description: "Plasma energy addresses the thin, papery skin that develops on legs with aging." }, { area: "Knee Laxity", description: "The knee area is particularly prone to sagging — targeted treatment firms and smooths." }, { area: "Post-Weight-Loss Skin", description: "Addresses excess skin laxity after significant weight loss without surgery." }, { area: "Loss of Elasticity", description: "Collagen and elastin stimulation restores the skin's structural integrity." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};