// src/content/services/jet-plasma-arm.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Jet Plasma Arm Chicago | $295 | Essence Medspa", description: "Jet Plasma arm treatment at Essence Medspa Chicago. 30-minute treatment for crepey arms. $295.", keywords: ["jet plasma arm Chicago", "jet plasma arm near me"], canonical: "https://www.essence-medspa.com/services/jet-plasma-arm" },
  hero: { eyebrow: "Body Treatments", headline: "Address Crepey, Aging Arm Skin", subheadline: "30-minute arm treatment for crepey skin, loss of elasticity, and visible aging on the upper arms.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$295 · 30 minutes", image: { src: "/images/services/jet-plasma-arm-hero.jpg", alt: "Address Crepey, Aging Arm Skin at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "30-minute arm treatment for crepey skin, loss of elasticity, and visible aging on the upper arms.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "30 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$295" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Crepey Arm Skin", description: "Plasma energy stimulates collagen and elastin production to firm thin, papery arm skin." }, { area: "Loss of Elasticity", description: "Restores the skin's ability to snap back rather than hanging loosely." }, { area: "Upper Arm Aging", description: "Addresses the visible aging that makes many people self-conscious about sleeveless clothing." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};