// src/content/services/jet-plasma-scalp.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Jet Plasma Scalp Chicago | $300 | Essence Medspa", description: "Jet Plasma scalp treatment at Essence Medspa Chicago. 30-minute treatment for hair loss, oily/dry scalp. $300.", keywords: ["jet plasma scalp Chicago", "jet plasma scalp near me"], canonical: "https://www.essence-medspa.com/services/jet-plasma-scalp" },
  hero: { eyebrow: "Body Treatments", headline: "Optimize Your Scalp Environment", subheadline: "30-minute scalp treatment for hair loss support, oily scalp, dry scalp, and dandruff. Creates the ideal conditions for healthy hair growth.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$300 · 30 minutes", image: { src: "/images/services/jet-plasma-scalp-hero.jpg", alt: "Optimize Your Scalp Environment at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "30-minute scalp treatment for hair loss support, oily scalp, dry scalp, and dandruff. Creates the ideal conditions for healthy hair growth.\n\nThis treatment is performed by our licensed specialists using professional-grade equipment and products for safe, effective results.", keyFacts: [{ label: "Treatment Time", value: "30 minutes" }, { label: "Downtime", value: "Minimal to none" }, { label: "Price", value: "$300" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Hair Loss Support", description: "Improves scalp circulation and health to create an optimal environment for hair growth." }, { area: "Oily Scalp", description: "Regulates sebum production for a balanced scalp." }, { area: "Dry Scalp & Dandruff", description: "Addresses flaking, itching, and dryness that compromise scalp health." }, { area: "Follicle Health", description: "Clears buildup around follicles that can impede healthy hair growth." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Consultation", description: "Brief assessment to confirm the treatment plan for your specific needs." }, { step: "02", title: "Preparation", description: "The treatment area is cleansed and prepped for optimal results." }, { step: "03", title: "Treatment", description: "The core treatment is performed with professional technique and attention to your comfort." }, { step: "04", title: "Aftercare", description: "Finishing products are applied and you receive aftercare instructions." }] },
  faqs: [
    { question: "How many sessions will I need?", answer: "Results vary by individual. Most clients see improvement after 1–2 sessions, with optimal results from a series of 3–6 treatments. We'll create a plan during your consultation." },
    { question: "Is there downtime?", answer: "Most treatments have minimal to no downtime. Your specialist will provide specific aftercare based on your treatment." },
    { question: "Can this be combined with other treatments?", answer: "Yes — many body treatments complement each other. Ask about combination protocols during your consultation." },
  ],
  relatedServices: { headline: "Related Treatments", items: [{ name: "Body Scrub", slug: "body-scrub", tagline: "Full-body exfoliation and renewal" }, { name: "Back Facial", slug: "back-facial", tagline: "Deep cleansing for back skin" }] },
  finalCTA: { headline: "Ready to Begin?", subheadline: "Book your treatment today.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};