// src/content/services/lipo-sculpt.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Lipo Sculpt Chicago | Non-Invasive Body Contouring | Starting at $300 | Essence Medspa", description: "Non-invasive body contouring at Essence Medspa Chicago. Target stubborn fat on abdomen, flanks, thighs, and arms. Starting at $300. No surgery, no downtime.", keywords: ["Lipo Sculpt Chicago", "body contouring near me", "non-invasive fat reduction Edgebrook", "body sculpting Chicago"], canonical: "https://www.essence-medspa.com/services/lipo-sculpt" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Sculpt Away What Diet and Exercise Can't", subheadline: "Lipo Sculpt targets and reduces stubborn fat deposits without surgery, without needles, and without downtime. Measurable results that develop naturally over 4–8 weeks.", primaryCTA: { text: "Book Consultation", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "Starting at $300 · No Surgery Required", image: { src: "/images/services/lipo-sculpt-hero.jpg", alt: "Non-invasive body contouring treatment at Essence Medspa Chicago" } },
  overview: { headline: "What Is Lipo Sculpt?", body: "Lipo Sculpt is a non-invasive body contouring treatment that targets stubborn fat deposits in areas that resist diet and exercise. The treatment disrupts fat cells in the targeted area, which your body then naturally processes and eliminates through the lymphatic system over the following 4–8 weeks.\n\nThis isn't weight loss — it's body sculpting. Lipo Sculpt is designed for clients who are near their ideal weight but have specific pockets of fat that won't respond to their lifestyle. The treatment requires no incisions, no anesthesia, and no recovery time.", keyFacts: [{ label: "Treatment Time", value: "45–60 minutes" }, { label: "Results Timeline", value: "4–8 weeks" }, { label: "Results", value: "20–25% fat reduction per cycle" }, { label: "Downtime", value: "None" }, { label: "Starting Price", value: "$300" }, { label: "Sessions Recommended", value: "2–4" }] },
  benefits: { headline: "What Lipo Sculpt Treats", items: [{ area: "Abdomen", description: "Target belly fat and love handles that persist despite core workouts and clean eating." }, { area: "Flanks (Love Handles)", description: "Reduce the fat deposits along the sides of the torso for a more streamlined silhouette." }, { area: "Thighs", description: "Address inner and outer thigh pockets for more proportional, toned-looking legs." }, { area: "Upper Arms", description: "Reduce stubborn arm fat for a more defined, toned appearance." }, { area: "Double Chin (Submental)", description: "Non-surgical chin fat reduction for a sharper jawline profile." }] },
  process: { headline: "Your Lipo Sculpt Experience", steps: [{ step: "01", title: "Consultation & Measurements", description: "We assess your problem areas, take circumference measurements, and create a treatment plan with realistic expectations." }, { step: "02", title: "Treatment", description: "The Lipo Sculpt device is applied to the target area for 45–60 minutes. Most clients read or relax during treatment." }, { step: "03", title: "Massage & Activation", description: "A brief massage after treatment helps activate the body's lymphatic processing of the disrupted fat cells." }, { step: "04", title: "Natural Elimination", description: "Your body processes the treated fat cells over 4–8 weeks. We measure again at your follow-up to track progress." }] },
  faqs: [
    { question: "How much fat can I lose?", answer: "Each treatment cycle typically reduces fat in the treated area by 20–25%. This is contouring, not weight loss — ideal for specific pockets rather than overall body fat reduction." },
    { question: "Is it permanent?", answer: "The disrupted fat cells are permanently eliminated. However, remaining cells can expand if you gain significant weight. Maintaining a stable weight preserves your results." },
    { question: "Does it hurt?", answer: "Most clients describe the sensation as pulling, tugging, or mild pressure. It's not painful, and many clients relax or nap during the session." },
    { question: "When will I see results?", answer: "Results develop gradually over 4–8 weeks as your body naturally eliminates the treated fat cells. Full results are typically visible at 12 weeks." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Meso Contour", slug: "meso-contour", tagline: "Precision sculpting for smaller areas" }, { name: "Body Scrub", slug: "body-scrub", tagline: "Improve circulation and skin texture" }, { name: "IV Therapy — Recovery", slug: "iv-therapy-recovery", tagline: "Support your body's elimination process" }] },
  finalCTA: { headline: "Ready to Sculpt Your Silhouette?", subheadline: "Book a body contouring consultation. We'll measure your target areas and create a plan with realistic timelines.", primaryCTA: { text: "Book Consultation", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
