// src/content/services/meso-firm.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Meso Firm Chicago | Skin Tightening Treatment | Starting at $125 | Essence Medspa", description: "Meso Firm at Essence Medspa Chicago. Mesotherapy micro-injections for skin tightening, elasticity restoration, and firming. Starting at $125. Book today.", keywords: ["meso firm Chicago", "skin tightening mesotherapy", "firming treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/meso-firm" },
  hero: { eyebrow: "Advanced Aesthetics · Mesotherapy", headline: "Tighter, Firmer, More Youthful Skin", subheadline: "Meso Firm delivers firming and elastin-stimulating compounds directly into lax skin through micro-injections. Restores the bounce and resilience your skin has been losing.", primaryCTA: { text: "Book Meso Firm", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "Starting at $125", image: { src: "/images/services/meso-firm-hero.jpg", alt: "Meso Firm skin tightening treatment at Essence Medspa Chicago" } },
  overview: { headline: "What Is Meso Firm?", body: "Meso Firm uses mesotherapy micro-injections to deliver a cocktail of firming agents, hyaluronic acid, vitamins, and elastin-stimulating peptides directly into the middle layer of the skin. This approach bypasses the skin barrier to work where laxity actually originates.\n\nAs we age, our skin produces less collagen and elastin — the proteins responsible for firmness and bounce. Topical creams can only reach the surface. Meso Firm delivers active ingredients precisely where they're needed to stimulate new collagen and elastin production, tighten existing fibers, and restore the structural integrity of your skin.", keyFacts: [{ label: "Treatment Time", value: "30–45 minutes" }, { label: "Results Timeline", value: "2–4 weeks per session" }, { label: "Sessions Recommended", value: "4–6" }, { label: "Downtime", value: "Minimal (24-hour redness)" }, { label: "Starting Price", value: "$125" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Skin Laxity", description: "Restores firmness to sagging skin on the face, neck, and jawline." }, { area: "Loss of Elasticity", description: "Stimulates elastin production so skin bounces back instead of drooping." }, { area: "Early Jowling", description: "Tightens the lower face to address the beginnings of jawline softening." }, { area: "Neck Laxity", description: "Firms loose neck skin — one of the first areas to show aging." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Assessment", description: "We evaluate your skin's elasticity and laxity to customize the firming cocktail concentration." }, { step: "02", title: "Micro-Injections", description: "The firming solution is delivered through precise micro-injections across the treatment area." }, { step: "03", title: "Aftercare", description: "Mild redness resolves within 24 hours. Avoid heavy exercise and heat for the day." }, { step: "04", title: "Progressive Firming", description: "Skin tightens progressively with each session as new collagen and elastin fibers form." }] },
  faqs: [
    { question: "How many sessions for visible tightening?", answer: "Most clients notice improvement after 2–3 sessions. For significant laxity, we recommend 4–6 sessions spaced 2–3 weeks apart, followed by maintenance every 2–3 months." },
    { question: "Can Meso Firm replace a facelift?", answer: "It's excellent for mild to moderate laxity. For significant sagging, it may be combined with other treatments. It won't produce the dramatic lift of surgery, but it avoids all surgical risks and downtime." },
    { question: "What areas can be treated?", answer: "Face, jawline, neck, décolleté, and upper arms are the most common areas. The cocktail is customized for each zone." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Meso Lift", slug: "meso-lift", tagline: "Add a lifting component for sagging skin" }, { name: "RF Micro-Needling", slug: "rf-microneedling-facial", tagline: "Deep collagen remodeling for enhanced firmness" }, { name: "Firming Facial", slug: "firming-facial", tagline: "Surface-level firming between meso sessions" }] },
  finalCTA: { headline: "Ready for Firmer Skin?", subheadline: "Book a consultation and we'll assess your skin's elasticity and recommend a firming protocol.", primaryCTA: { text: "Book Meso Firm", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
