// src/content/services/meso-lift.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Meso Lift Chicago | Non-Surgical Lifting | Starting at $125 | Essence Medspa", description: "Meso Lift at Essence Medspa Chicago. Mesotherapy lifting cocktail to smooth, tone, and lift skin while stimulating collagen production. Starting at $125.", keywords: ["meso lift Chicago", "non-surgical face lift mesotherapy", "skin lifting treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/meso-lift" },
  hero: { eyebrow: "Advanced Aesthetics · Mesotherapy", headline: "Smooth. Tone. Lift.", subheadline: "Meso Lift delivers a powerful lifting cocktail through micro-injections to tighten, tone, and lift sagging skin. Stimulates collagen production for progressive, natural-looking lifting results.", primaryCTA: { text: "Book Meso Lift", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "Starting at $125 · Non-Surgical Lift", image: { src: "/images/services/meso-lift-hero.jpg", alt: "Meso Lift non-surgical skin lifting treatment at Essence Medspa" } },
  overview: { headline: "What Is Meso Lift?", body: "Meso Lift uses mesotherapy to deliver a specialized lifting cocktail containing DMAE (dimethylaminoethanol), peptides, hyaluronic acid, and collagen-stimulating amino acids directly into the skin. DMAE has a unique ability to temporarily tighten and tone muscles beneath the skin, creating an immediate lifting effect.\n\nOver the following weeks, the peptides and amino acids stimulate new collagen production, making the lift progressively more pronounced and longer-lasting. Meso Lift is the mesotherapy treatment most directly comparable to a non-surgical facelift — it addresses both the immediate visible sag and the underlying collagen loss that caused it.", keyFacts: [{ label: "Treatment Time", value: "30–45 minutes" }, { label: "Results", value: "Immediate tightening + progressive lift" }, { label: "Sessions Recommended", value: "4–6" }, { label: "Downtime", value: "Minimal (24-hour redness)" }, { label: "Starting Price", value: "$125" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Sagging Cheeks", description: "The lifting cocktail tightens and tones the midface for a more defined cheekbone structure." }, { area: "Jawline Softening", description: "Restores definition to a jawline that's losing its sharp contour." }, { area: "Jowl Formation", description: "Addresses early jowling by tightening the lower face and stimulating collagen in the area." }, { area: "Neck Sagging", description: "Firms and lifts the neck area for a smoother, more youthful profile." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Laxity Assessment", description: "We evaluate which areas have the most laxity and customize the injection plan." }, { step: "02", title: "Lifting Injections", description: "The DMAE-based lifting cocktail is delivered through micro-injections across the treatment zones." }, { step: "03", title: "Immediate Effect", description: "You'll notice a tightening effect immediately as DMAE activates muscle tone." }, { step: "04", title: "Progressive Lift", description: "Collagen stimulation continues for weeks, making each session build on the last." }] },
  faqs: [
    { question: "What's the difference between Meso Lift and Meso Firm?", answer: "Meso Firm focuses on elasticity and skin bounce. Meso Lift specifically targets muscle tone and lifting through DMAE, plus longer-term collagen stimulation. Firm is about skin quality; Lift is about repositioning sagging tissue." },
    { question: "Can I combine Meso Lift with other treatments?", answer: "Yes — it pairs especially well with Meso Firm for comprehensive skin tightening, or with Botox to address both sagging and dynamic wrinkles." },
    { question: "How long does the lifting effect last?", answer: "The immediate DMAE effect lasts 2–3 weeks. With a series of 4–6 treatments, the collagen-building effect creates progressively longer-lasting lift. Maintenance every 4–6 weeks sustains results." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Meso Firm", slug: "meso-firm", tagline: "Add elasticity restoration for comprehensive tightening" }, { name: "Botox", slug: "botox", tagline: "Address wrinkles alongside lifting" }, { name: "4D Face Lifting Massage", slug: "4d-face-lifting-massage", tagline: "Manual lifting complement" }] },
  finalCTA: { headline: "Ready for a Non-Surgical Lift?", subheadline: "Book a consultation and we'll assess your lifting needs and create a targeted protocol.", primaryCTA: { text: "Book Meso Lift", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
