// src/content/services/meso-contour.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Meso Contour Chicago | Non-Surgical Sculpting | Starting at $125 | Essence Medspa", description: "Meso Contour at Essence Medspa Chicago. Mesotherapy micro-injections for non-surgical body sculpting, double chin reduction, and post-weight-loss contouring. Starting at $125.", keywords: ["meso contour Chicago", "mesotherapy body sculpting", "double chin treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/meso-contour" },
  hero: { eyebrow: "Advanced Aesthetics · Mesotherapy", headline: "Precision Sculpting Without Surgery", subheadline: "Meso Contour uses targeted micro-injections to sculpt and define areas that need precision work — double chin, bra bulge, inner knees, and more. Non-surgical body contouring at its most precise.", primaryCTA: { text: "Book Meso Contour", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "Starting at $125", image: { src: "/images/services/meso-contour-hero.jpg", alt: "Meso Contour body sculpting treatment at Essence Medspa" } },
  overview: { headline: "What Is Meso Contour?", body: "Meso Contour delivers a specialized contouring cocktail through mesotherapy micro-injections directly into targeted fat deposits. The solution disrupts fat cells at the injection site, which your body then naturally metabolizes and eliminates.\n\nWhere Lipo Sculpt works best for larger areas, Meso Contour excels at precision — small, stubborn pockets like the double chin, bra bulge, inner knees, and upper arm pockets. It's also an excellent option for post-weight-loss clients who need fine-tuning rather than major fat reduction.", keyFacts: [{ label: "Treatment Time", value: "30–45 minutes" }, { label: "Results Timeline", value: "2–4 weeks per session" }, { label: "Sessions Recommended", value: "3–6" }, { label: "Downtime", value: "1–3 days mild swelling" }, { label: "Starting Price", value: "$125" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Double Chin", description: "Precise fat dissolution along the submental area for a sharper jawline and defined profile." }, { area: "Bra Bulge", description: "Target the fat roll along the bra line that's visible in fitted clothing." }, { area: "Inner Knees", description: "Reduce the small fat pocket above the inner knee for smoother leg contour." }, { area: "Post-Weight-Loss Refinement", description: "Fine-tune body contours after significant weight loss where pockets remain." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Assessment & Marking", description: "We identify and mark the precise treatment zones for targeted injection." }, { step: "02", title: "Micro-Injections", description: "The contouring cocktail is delivered through a series of micro-injections into the fat layer." }, { step: "03", title: "Post-Treatment", description: "Brief massage to distribute the solution. Mild swelling and tenderness for 1–3 days." }, { step: "04", title: "Natural Processing", description: "Your body metabolizes the disrupted fat cells over 2–4 weeks. Progressive improvement with each session." }] },
  faqs: [
    { question: "What's the difference between Meso Contour and Lipo Sculpt?", answer: "Lipo Sculpt covers larger areas externally (abdomen, thighs). Meso Contour uses micro-injections for precision sculpting of smaller areas. Think of Lipo Sculpt as the broad brush and Meso Contour as the fine detail tool." },
    { question: "How many sessions for double chin reduction?", answer: "Most clients see significant improvement in 3–4 sessions spaced 3–4 weeks apart. The number depends on the amount of submental fat present." },
    { question: "Does it hurt?", answer: "The micro-injections cause a mild stinging sensation. Topical numbing is available for sensitive clients. Post-treatment tenderness is similar to a mild bruise." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Lipo Sculpt", slug: "lipo-sculpt", tagline: "Larger area contouring" }, { name: "Meso Firm", slug: "meso-firm", tagline: "Tighten skin after fat reduction" }] },
  finalCTA: { headline: "Ready for Precision Sculpting?", subheadline: "Book a consultation. We'll assess your areas of concern and create a targeted contouring plan.", primaryCTA: { text: "Book Meso Contour", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
