// src/content/services/meso-brightening.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Meso Brightening Chicago | Dark Spots & Pigmentation | Starting at $125 | Essence Medspa", description: "Meso Brightening at Essence Medspa Chicago. Mesotherapy micro-injections to fade dark spots, melasma, and uneven skin tone. Starting at $125.", keywords: ["meso brightening Chicago", "mesotherapy pigmentation treatment", "dark spots treatment Edgebrook"], canonical: "https://www.essence-medspa.com/services/meso-brightening" },
  hero: { eyebrow: "Advanced Aesthetics · Mesotherapy", headline: "Fade Dark Spots at the Source", subheadline: "Meso Brightening delivers potent brightening agents directly into the pigmented layers of your skin through micro-injections. No surface-level products — this treats discoloration where it actually lives.", primaryCTA: { text: "Book Meso Brightening", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "Starting at $125", image: { src: "/images/services/meso-brightening-hero.jpg", alt: "Meso Brightening treatment for hyperpigmentation at Essence Medspa Chicago" } },
  overview: { headline: "What Is Meso Brightening?", body: "Meso Brightening uses mesotherapy — a technique of precise micro-injections — to deliver a cocktail of brightening agents, antioxidants, and melanin inhibitors directly into the mesodermal layer of the skin where pigmentation originates.\n\nUnlike topical brightening products that only reach the surface, mesotherapy bypasses the skin barrier entirely. The active ingredients work at the cellular level to inhibit tyrosinase (the enzyme that produces melanin), break up existing pigment clusters, and prevent new dark spots from forming. This makes it one of the most effective treatments for stubborn hyperpigmentation, melasma, and post-inflammatory marks.", keyFacts: [{ label: "Treatment Time", value: "30–45 minutes" }, { label: "Results Timeline", value: "After 2–3 sessions" }, { label: "Sessions Recommended", value: "4–6" }, { label: "Downtime", value: "Minimal (1 day redness)" }, { label: "Starting Price", value: "$125" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Hyperpigmentation", description: "Sun spots, age spots, and post-inflammatory marks are targeted directly at the melanocyte level." }, { area: "Melasma", description: "Hormonal pigmentation responds well to mesotherapy's deep delivery of tyrosinase inhibitors." }, { area: "Uneven Skin Tone", description: "Overall tone evens out as melanin production normalizes across the treated area." }, { area: "Post-Acne Marks", description: "Dark marks left behind after acne heal faster with targeted brightening agents." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Skin Assessment", description: "We evaluate your pigmentation type, depth, and triggers to customize the brightening cocktail." }, { step: "02", title: "Micro-Injections", description: "The brightening solution is delivered through a series of precise micro-injections into the affected areas." }, { step: "03", title: "Soothing Application", description: "A calming serum and SPF are applied. Mild redness resolves within 24 hours." }, { step: "04", title: "Progressive Results", description: "Pigmentation lightens progressively with each session. Most clients see noticeable improvement after 2–3 treatments." }] },
  faqs: [
    { question: "How many Meso Brightening sessions do I need?", answer: "4–6 sessions spaced 2–3 weeks apart for optimal results. Stubborn melasma may require additional sessions. Maintenance every 2–3 months prevents recurrence." },
    { question: "Is it safe for dark skin tones?", answer: "Yes, when performed by a trained specialist. We adjust the cocktail formulation and intensity for darker skin types to avoid triggering rebound pigmentation." },
    { question: "Can I combine this with other brightening treatments?", answer: "Absolutely. We often combine Meso Brightening with Glutathione IV pushes for inside-out brightening, or with a Brightening Facial for surface-level correction." },
    { question: "Will my dark spots come back?", answer: "They can if triggers aren't managed. We recommend daily SPF 50, avoiding direct sun exposure, and maintenance sessions to keep results long-term." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Glutathione Brightening", slug: "glutathione-brightening", tagline: "Internal brightening to complement external treatment" }, { name: "Brightening Facial", slug: "brightening-facial", tagline: "Surface-level brightness boost" }, { name: "Custom Peel", slug: "custom-peel", tagline: "Exfoliate pigmented surface cells" }] },
  finalCTA: { headline: "Ready for a More Even Complexion?", subheadline: "Book a consultation. We'll assess your pigmentation type and create a targeted brightening plan.", primaryCTA: { text: "Book Meso Brightening", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
