// src/content/services/meso-glow.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Meso Glow Chicago | Radiance & Hydration Treatment | Starting at $125 | Essence Medspa", description: "Meso Glow at Essence Medspa Chicago. Nourishing mesotherapy serums delivered via micro-needling for instant radiance and lasting hydration. Starting at $125.", keywords: ["meso glow Chicago", "mesotherapy glow treatment", "skin radiance Edgebrook", "glow facial Chicago"], canonical: "https://www.essence-medspa.com/services/meso-glow" },
  hero: { eyebrow: "Advanced Aesthetics · Mesotherapy", headline: "The Lit-From-Within Treatment", subheadline: "Meso Glow floods your skin with nourishing serums, hyaluronic acid, and vitamins through micro-needling. The result is deep hydration, instant radiance, and a lasting lit-from-within glow.", primaryCTA: { text: "Book Meso Glow", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "Starting at $125 · Instant Glow", image: { src: "/images/services/meso-glow-hero.jpg", alt: "Radiant glowing skin after Meso Glow treatment at Essence Medspa" } },
  overview: { headline: "What Is Meso Glow?", body: "Meso Glow combines mesotherapy with micro-needling to deliver a customized cocktail of hyaluronic acid, vitamins (C, E, B complex), amino acids, and antioxidants deep into the skin. While topical serums sit on the surface, Meso Glow drives these active ingredients into the dermal layer where they produce maximum impact.\n\nThe treatment works on two levels: immediate surface hydration creates an instant glow, while the deeper nourishment stimulates ongoing cellular renewal and collagen production. Clients leave visibly more radiant and continue to improve over the following weeks.", keyFacts: [{ label: "Treatment Time", value: "30–45 minutes" }, { label: "Results", value: "Immediate glow + progressive improvement" }, { label: "Sessions Recommended", value: "3–6 for lasting results" }, { label: "Downtime", value: "None to minimal" }, { label: "Starting Price", value: "$125" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Dull, Tired Skin", description: "Deep vitamin and antioxidant infusion revives flat, lifeless skin with immediate luminosity." }, { area: "Dehydrated Skin", description: "Hyaluronic acid delivered at the dermal level provides deep hydration that topicals can't match." }, { area: "Uneven Texture", description: "Micro-needling smooths surface irregularities while serums nourish from within." }, { area: "Pre-Event Prep", description: "Instant glow with zero downtime makes this ideal before weddings, parties, or photo shoots." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Skin Cleansing", description: "Thorough double cleanse to prepare your skin for maximum absorption." }, { step: "02", title: "Micro-Needling + Serum Infusion", description: "Professional micro-needling drives the customized glow cocktail deep into your skin." }, { step: "03", title: "Hydrating Mask", description: "A nourishing mask seals in the active ingredients while you relax." }, { step: "04", title: "Glow Results", description: "You'll leave with visibly more radiant skin. The glow deepens over the following 48 hours." }] },
  faqs: [
    { question: "How soon can I wear makeup after Meso Glow?", answer: "We recommend waiting 4–6 hours for the micro-channels to close. Many clients find they don't want to — the natural glow is that noticeable." },
    { question: "How often should I get Meso Glow?", answer: "For event prep, a single session works beautifully. For lasting skin quality improvement, we recommend a series of 3–6 sessions spaced 2–4 weeks apart, then monthly maintenance." },
    { question: "Is Meso Glow good for dry skin?", answer: "It's one of the best treatments for chronic dehydration. The hyaluronic acid is delivered directly into the dermis where it holds up to 1,000 times its weight in water, providing hydration that lasts far longer than surface application." },
    { question: "Can I combine Meso Glow with other treatments?", answer: "Yes — it pairs beautifully with Glutathione IV for inside-out radiance, or as a prep treatment before a special event facial." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Glutathione Brightening", slug: "glutathione-brightening", tagline: "Internal glow to match external radiance" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "Deep cleansing before glow infusion" }, { name: "Oxygen Facial", slug: "oxygen-facial", tagline: "Oxygen-powered hydration boost" }] },
  finalCTA: { headline: "Ready to Glow?", subheadline: "Book your Meso Glow session. Instant radiance, lasting results.", primaryCTA: { text: "Book Meso Glow", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
