// src/content/services/microdermabrasion-neck.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Microdermabrasion Neck Chicago | $59 | Essence Medspa", description: "Microdermabrasion for neck at Essence Medspa Chicago. 20-minute treatment for neck lines and uneven tone. $59.", keywords: ["microdermabrasion neck Chicago", "microdermabrasion neck near me"], canonical: "https://www.essence-medspa.com/services/microdermabrasion-neck" },
  hero: { eyebrow: "Facial Treatments", headline: "Targeted Neck Renewal", subheadline: "A 20-minute crystal exfoliation for the neck area. Smooths lines, wrinkles, and uneven skin tone on one of the first areas to show aging.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$59 · 20 minutes", image: { src: "/images/services/microdermabrasion-neck-hero.jpg", alt: "Targeted Neck Renewal at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "A 20-minute crystal exfoliation for the neck area. Smooths lines, wrinkles, and uneven skin tone on one of the first areas to show aging. This professional treatment is performed by our licensed aestheticians using medical-grade products selected for maximum efficacy.\n\nEvery session begins with a skin assessment to ensure the treatment is tailored to your current skin condition and concerns.", keyFacts: [{ label: "Treatment Time", value: "20 minutes" }, { label: "Downtime", value: "None to minimal" }, { label: "Price", value: "$59" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Neck Lines", description: "Horizontal neck lines (necklace lines) are softened through exfoliation and collagen stimulation." }, { area: "Uneven Neck Tone", description: "Removes discolored surface cells for more uniform neck skin." }, { area: "Crepey Neck Texture", description: "Progressive treatments improve texture and firmness of thin neck skin." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Assessment", description: "Your aesthetician evaluates your skin and confirms the treatment plan." }, { step: "02", title: "Preparation", description: "Thorough cleansing and prep to maximize treatment effectiveness." }, { step: "03", title: "Active Treatment", description: "The core treatment protocol is applied with expert technique and professional products." }, { step: "04", title: "Finishing", description: "Protective finishing products and aftercare instructions to maintain your results." }] },
  faqs: [
    { question: "How often should I get this treatment?", answer: "Every 4–6 weeks for maintained results. Your aesthetician will recommend the ideal frequency for your skin." },
    { question: "Is there any downtime?", answer: "Most facial treatments have minimal to no downtime. Your aesthetician will advise on any specific post-treatment care." },
    { question: "Can this be combined with other treatments?", answer: "Many treatments complement each other well. Ask your aesthetician about combination protocols during your visit." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Custom Facial", slug: "custom-facial", tagline: "Fully personalized treatment" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "Device-driven cleansing and glow" }] },
  finalCTA: { headline: "Ready for Beautiful Skin?", subheadline: "Book your treatment today. Expert care, visible results.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};