// src/content/services/microdermabrasion-chest.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Microdermabrasion Chest Chicago | $91 | Essence Medspa", description: "Microdermabrasion for chest at Essence Medspa Chicago. 45-minute décolleté treatment for sun damage and age spots. $91.", keywords: ["microdermabrasion chest Chicago", "microdermabrasion chest near me"], canonical: "https://www.essence-medspa.com/services/microdermabrasion-chest" },
  hero: { eyebrow: "Facial Treatments", headline: "Smooth and Renew the Décolleté", subheadline: "A 45-minute crystal exfoliation specifically for the chest area. Targets sun damage, age spots, and fine lines on the décolleté.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$91 · 45 minutes", image: { src: "/images/services/microdermabrasion-chest-hero.jpg", alt: "Smooth and Renew the Décolleté at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "A 45-minute crystal exfoliation specifically for the chest area. Targets sun damage, age spots, and fine lines on the décolleté. This professional treatment is performed by our licensed aestheticians using medical-grade products selected for maximum efficacy.\n\nEvery session begins with a skin assessment to ensure the treatment is tailored to your current skin condition and concerns.", keyFacts: [{ label: "Treatment Time", value: "45 minutes" }, { label: "Downtime", value: "None to minimal" }, { label: "Price", value: "$91" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Chest Sun Damage", description: "Crystal exfoliation removes sun-damaged cells on the décolleté — an area that shows UV damage early." }, { area: "Age Spots", description: "Progressive treatments lift pigmented spots from the chest area." }, { area: "Fine Lines on Chest", description: "Exfoliation and collagen stimulation smooth lines caused by sun exposure and aging." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Assessment", description: "Your aesthetician evaluates your skin and confirms the treatment plan." }, { step: "02", title: "Preparation", description: "Thorough cleansing and prep to maximize treatment effectiveness." }, { step: "03", title: "Active Treatment", description: "The core treatment protocol is applied with expert technique and professional products." }, { step: "04", title: "Finishing", description: "Protective finishing products and aftercare instructions to maintain your results." }] },
  faqs: [
    { question: "How often should I get this treatment?", answer: "Every 4–6 weeks for maintained results. Your aesthetician will recommend the ideal frequency for your skin." },
    { question: "Is there any downtime?", answer: "Most facial treatments have minimal to no downtime. Your aesthetician will advise on any specific post-treatment care." },
    { question: "Can this be combined with other treatments?", answer: "Many treatments complement each other well. Ask your aesthetician about combination protocols during your visit." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Custom Facial", slug: "custom-facial", tagline: "Fully personalized treatment" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "Device-driven cleansing and glow" }] },
  finalCTA: { headline: "Ready for Beautiful Skin?", subheadline: "Book your treatment today. Expert care, visible results.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};