// src/content/services/prenatal-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Prenatal Massage Chicago | $159–$199 | Essence Medspa", description: "Comfort and Relief for Moms-to-Be 50 or 80-minute safe pregnancy massage with specialized positioning. Addresses the unique aches, swe... At Essence Medspa Chicago. $159–$199.", keywords: ["prenatal massage Chicago", "prenatal massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/prenatal-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Comfort and Relief for Moms-to-Be", subheadline: "50 or 80-minute safe pregnancy massage with specialized positioning. Addresses the unique aches, swelling, and discomfort of pregnancy.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$159–$199", image: { src: "/images/services/prenatal-massage-hero.jpg", alt: "Comfort and Relief for Moms-to-Be at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50 or 80-minute safe pregnancy massage with specialized positioning. Addresses the unique aches, swelling, and discomfort of pregnancy.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$159–$199" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Lower Back Pain", description: "The most common pregnancy complaint — targeted work on the lumbar region provides significant relief." }, { area: "Swelling & Edema", description: "Gentle lymphatic techniques reduce fluid retention in legs, ankles, and hands." }, { area: "Hip & Sciatic Pain", description: "Focused attention on the glutes, piriformis, and hip flexors addresses radiating sciatic pain." }, { area: "General Pregnancy Discomfort", description: "Full-body relaxation helps manage the cumulative physical stress of pregnancy." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};