// src/content/services/prf-under-eyes.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "PRF Under Eyes Chicago | Dark Circles Treatment | $300 | Essence Medspa", description: "PRF under-eye treatment at Essence Medspa Chicago. Natural volume restoration and dark circle correction without fillers. $300. No migration risk. Free consultation.", keywords: ["PRF under eyes Chicago", "dark circles treatment near me", "under eye rejuvenation Edgebrook", "PRF eye treatment Chicago"], canonical: "https://www.essence-medspa.com/services/prf-under-eyes" },
  hero: { eyebrow: "Advanced Aesthetics", headline: "Brighten and Plump — Without Fillers", subheadline: "PRF under eyes uses your own platelet-rich fibrin to naturally restore volume, brighten dark circles, and rejuvenate the delicate under-eye area. Zero filler migration risk.", primaryCTA: { text: "Book PRF Under Eyes", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$300 · No Filler Required", image: { src: "/images/services/prf-under-eyes-hero.jpg", alt: "Natural under-eye rejuvenation with PRF treatment at Essence Medspa" } },
  overview: { headline: "What Is PRF Under Eyes?", body: "The under-eye area is one of the most delicate zones on the face — and one of the first places that shows aging, fatigue, and volume loss. Traditional fillers carry risks in this area including migration, the Tyndall effect (a bluish tint), and lumpiness.\n\nPRF offers a safer alternative. By injecting platelet-rich fibrin from your own blood beneath the eyes, we stimulate natural collagen production and tissue regeneration. The fibrin matrix acts as a scaffold, slowly releasing growth factors over 10–12 days. The result is gradual, natural-looking volume restoration and brightening — without the risks associated with synthetic fillers.", keyFacts: [{ label: "Treatment Time", value: "30–45 minutes" }, { label: "Results Timeline", value: "4–6 weeks" }, { label: "Results Last", value: "6–12 months" }, { label: "Downtime", value: "2–3 days mild swelling" }, { label: "Price", value: "$300" }, { label: "Sessions Recommended", value: "1–2" }] },
  benefits: { headline: "What PRF Under Eyes Treats", items: [{ area: "Dark Circles", description: "PRF improves blood supply and tissue quality beneath the eyes, reducing the shadowed, hollow appearance that causes dark circles." }, { area: "Hollow Under Eyes", description: "The fibrin matrix stimulates tissue regeneration that naturally fills the tear trough area over 4–6 weeks." }, { area: "Fine Lines Under Eyes", description: "Growth factors drive collagen production in the thin under-eye skin, softening crepe-like lines and improving elasticity." }, { area: "Tired Appearance", description: "By restoring volume and improving skin quality, PRF eliminates the \"always tired\" look that makes you appear older than you feel." }] },
  process: { headline: "Your PRF Under Eye Experience", steps: [{ step: "01", title: "Blood Draw & Processing", description: "A small blood sample is drawn and processed in a centrifuge to create the platelet-rich fibrin concentrate." }, { step: "02", title: "Numbing", description: "Topical numbing cream is applied to the under-eye area for maximum comfort." }, { step: "03", title: "Precise Injection", description: "PRF is carefully injected into the tear trough and under-eye area using a fine needle. The process takes about 15 minutes." }, { step: "04", title: "Gradual Improvement", description: "Mild swelling for 2–3 days. Natural improvement begins at week 2 and continues building through week 6." }] },
  faqs: [
    { question: "Why PRF instead of filler under the eyes?", answer: "The under-eye area has very thin skin with limited tissue support. Hyaluronic acid fillers can migrate, cause a bluish tint (Tyndall effect), or look lumpy in this zone. PRF uses your own blood and stimulates natural tissue regeneration, eliminating these risks entirely." },
    { question: "How long until I see results?", answer: "You'll notice initial improvement around week 2, with results continuing to build through week 4–6 as collagen production increases. The gradual nature means the results look completely natural." },
    { question: "How long do results last?", answer: "Most clients enjoy results for 6–12 months. A second session 4–6 weeks after the first maximizes and extends the benefit." },
    { question: "Is there bruising?", answer: "Mild bruising is possible given the delicate under-eye tissue. It typically resolves within 5–7 days. We recommend avoiding blood thinners and alcohol 48 hours before treatment to minimize bruising." },
  ],
  relatedServices: { headline: "Often Combined With", items: [{ name: "Collagen Sublime Eye Contour", slug: "collagen-eye-contour", tagline: "Surface nourishment between PRF sessions" }, { name: "PRF Facial", slug: "prf-facial", tagline: "Full-face regeneration" }, { name: "Glutathione Brightening", slug: "glutathione-brightening", tagline: "Internal brightening to complement external treatment" }] },
  finalCTA: { headline: "Ready to Brighten Your Under Eyes Naturally?", subheadline: "Book a consultation and learn how PRF can restore your under-eye area without the risks of traditional fillers.", primaryCTA: { text: "Book PRF Under Eyes", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};
