// src/content/services/swedish-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Swedish Massage Chicago | $109–$145 | Essence Medspa", description: "The Classic. The Essential. The Reset. 50 or 80-minute soothing massage using long, flowing strokes to dissolve tension, improve circulatio... At Essence Medspa Chicago. $109–$145.", keywords: ["swedish massage Chicago", "swedish massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/swedish-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "The Classic. The Essential. The Reset.", subheadline: "50 or 80-minute soothing massage using long, flowing strokes to dissolve tension, improve circulation, and promote deep relaxation. The foundation of therapeutic massage.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$109–$145", image: { src: "/images/services/swedish-massage-hero.jpg", alt: "The Classic. The Essential. The Reset. at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50 or 80-minute soothing massage using long, flowing strokes to dissolve tension, improve circulation, and promote deep relaxation. The foundation of therapeutic massage.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$109–$145" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "General Stress & Tension", description: "Long, flowing strokes activate the parasympathetic nervous system for deep relaxation." }, { area: "Poor Circulation", description: "Effleurage and petrissage techniques improve blood and lymphatic flow." }, { area: "Muscle Stiffness", description: "Gentle kneading releases mild muscle tension without the intensity of deep tissue." }, { area: "Sleep Issues", description: "The deeply relaxing effect helps regulate sleep patterns for many clients." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};