// src/content/services/teen-facial.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Teen Facial Chicago | $85 | Essence Medspa", description: "Teen facial at Essence Medspa Chicago. 30-minute facial for ages 13-19 with deep cleansing, acne care, and skincare education. $85.", keywords: ["teen facial Chicago", "teen facial near me"], canonical: "https://www.essence-medspa.com/services/teen-facial" },
  hero: { eyebrow: "Facial Treatments", headline: "The Right Start for Young Skin", subheadline: "A 30-minute facial designed specifically for teens ages 13–19. Deep cleansing, gentle acne management, and skincare education — building healthy habits early.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$85 · 30 minutes", image: { src: "/images/services/teen-facial-hero.jpg", alt: "The Right Start for Young Skin at Essence Medspa Chicago" } },
  overview: { headline: "About This Treatment", body: "A 30-minute facial designed specifically for teens ages 13–19. Deep cleansing, gentle acne management, and skincare education — building healthy habits early. This professional treatment is performed by our licensed aestheticians using medical-grade products selected for maximum efficacy.\n\nEvery session begins with a skin assessment to ensure the treatment is tailored to your current skin condition and concerns.", keyFacts: [{ label: "Treatment Time", value: "30 minutes" }, { label: "Downtime", value: "None to minimal" }, { label: "Price", value: "$85" }] },
  benefits: { headline: "What It Treats", items: [{ area: "Teen Acne", description: "Gentle but effective cleansing and extraction appropriate for young, hormonal skin." }, { area: "Oily Skin", description: "Oil-balancing products control shine without over-drying developing skin." }, { area: "Blackheads", description: "Professional extraction removes blackheads safely — much better than picking at home." }, { area: "Skincare Education", description: "Your teen learns proper cleansing, moisturizing, and SPF habits from a professional." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Assessment", description: "Your aesthetician evaluates your skin and confirms the treatment plan." }, { step: "02", title: "Preparation", description: "Thorough cleansing and prep to maximize treatment effectiveness." }, { step: "03", title: "Active Treatment", description: "The core treatment protocol is applied with expert technique and professional products." }, { step: "04", title: "Finishing", description: "Protective finishing products and aftercare instructions to maintain your results." }] },
  faqs: [
    { question: "How often should I get this treatment?", answer: "Every 4–6 weeks for maintained results. Your aesthetician will recommend the ideal frequency for your skin." },
    { question: "Is there any downtime?", answer: "Most facial treatments have minimal to no downtime. Your aesthetician will advise on any specific post-treatment care." },
    { question: "Can this be combined with other treatments?", answer: "Many treatments complement each other well. Ask your aesthetician about combination protocols during your visit." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Custom Facial", slug: "custom-facial", tagline: "Fully personalized treatment" }, { name: "Hydrofacial", slug: "hydrofacial", tagline: "Device-driven cleansing and glow" }] },
  finalCTA: { headline: "Ready for Beautiful Skin?", subheadline: "Book your treatment today. Expert care, visible results.", primaryCTA: { text: "Book Treatment", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};