// src/content/services/thai-herbal-massage.ts
import type { ServicePageContent } from "@/types/content";
export const content: ServicePageContent = {
  seo: { title: "Thai Herbal Massage Chicago | $166 | Essence Medspa", description: "Aromatic Herbs Meet Ancient Healing 50-minute massage using heated herbal compresses filled with aromatic Thai herbs. Natural harmony, d... At Essence Medspa Chicago. $166.", keywords: ["thai herbal massage Chicago", "thai herbal massage near me", "massage Edgebrook"], canonical: "https://www.essence-medspa.com/services/thai-herbal-massage" },
  hero: { eyebrow: "Therapeutic Massage", headline: "Aromatic Herbs Meet Ancient Healing", subheadline: "50-minute massage using heated herbal compresses filled with aromatic Thai herbs. Natural harmony, deep relaxation, and therapeutic herbal benefits in one treatment.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" }, badge: "$166", image: { src: "/images/services/thai-herbal-massage-hero.jpg", alt: "Aromatic Herbs Meet Ancient Healing at Essence Medspa Chicago" } },
  overview: { headline: "About This Massage", body: "50-minute massage using heated herbal compresses filled with aromatic Thai herbs. Natural harmony, deep relaxation, and therapeutic herbal benefits in one treatment.\n\nAll massage services at Essence Medspa are performed by licensed massage therapists (LMTs) with specialized training in their modality.", keyFacts: [{ label: "Price", value: "$166" }, { label: "Downtime", value: "None" }] },
  benefits: { headline: "What It Helps", items: [{ area: "Muscle Pain & Inflammation", description: "The heat and anti-inflammatory properties of Thai herbs penetrate muscles for natural pain relief." }, { area: "Joint Stiffness", description: "Herbal compresses applied to joints deliver both warmth and botanical healing compounds." }, { area: "Stress & Mental Fatigue", description: "The aromatic herbs create an immersive sensory experience that calms the mind." }, { area: "Skin Nourishment", description: "The herbs leave skin soft, fragrant, and nourished from the botanical oils." }] },
  process: { headline: "Your Experience", steps: [{ step: "01", title: "Intake", description: "Brief discussion about your tension areas, preferences, and any health considerations." }, { step: "02", title: "Treatment", description: "Your therapist customizes the session to your specific needs, adjusting pressure and focus areas." }, { step: "03", title: "Aftercare", description: "Water, recommendations for home care, and guidance on when to return for your next session." }] },
  faqs: [
    { question: "How often should I get this massage?", answer: "For maintenance: monthly. For active issues: weekly or biweekly until resolved. Your therapist will recommend the ideal frequency." },
    { question: "Can I request specific focus areas?", answer: "Absolutely — tell your therapist where you hold tension and they'll customize the entire session accordingly." },
  ],
  relatedServices: { headline: "Explore More", items: [{ name: "Swedish Massage", slug: "swedish-massage", tagline: "Classic relaxation" }, { name: "Deep Tissue", slug: "deep-tissue-massage", tagline: "Intensive relief" }, { name: "Hot Stone", slug: "hot-stone-massage", tagline: "Heat-enhanced healing" }] },
  finalCTA: { headline: "Ready to Unwind?", subheadline: "Book your massage today.", primaryCTA: { text: "Book Massage", href: "https://www.vagaro.com/essencemedspaandwellnesscenter/book-now", variant: "primary" }, secondaryCTA: { text: "Call (773) 763-1212", href: "tel:+17737631212", variant: "outline" } },
};